package xxgam.oracle.apps.xbol.maf.server.common;

import oracle.jbo.common.JboResourceBundle;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class XxGamMaFlightInf0EOImplMsgBundle extends JboResourceBundle {
    static final Object[][] sMessageStrings = 
    { { "DepartureDate_Rule_0", "La fecha de salida no puede ser menor a la fecha de retorno" } };

    /**This is the default constructor (do not remove)
     */
    public XxGamMaFlightInf0EOImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
