package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTicketOfficeLovVOImpl extends OAViewObjectImpl
{
    /**This is the default constructor (do not remove)
     */
    public XxGamMaTicketOfficeLovVOImpl() {
    }
    
    public String getTicketOfficeDescription(String lookUpCode){
        //Verifica nulidad
         clearViewCriterias();
         String description = null;
        if (lookUpCode == null)
            return null;
        try {
            //Declara los recursos    
            ViewCriteria vcTicketOffice = null;
            ViewCriteriaRow rowVCTicketOffice = null;

            //Crea el criterio de busqueda
            vcTicketOffice = createViewCriteria();
            rowVCTicketOffice = vcTicketOffice.createViewCriteriaRow();
            rowVCTicketOffice.setAttribute("LookupCode", lookUpCode);

            //Aplica el criterio
            vcTicketOffice.addElement(rowVCTicketOffice);
            applyViewCriteria(vcTicketOffice);
            executeQuery();
            clearViewCriterias();
            //Inicializa el current row
            if (getEstimatedRowCount() > 0) {
               description  = String.valueOf(first().getAttribute("Meaning"));
            }
        } catch (Exception exception) {
            clearViewCriterias();
        }   
        return description;
    }
}
