package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaApproverHierarchyLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaApproverHierarchyLovVOImpl extends OAViewObjectImpl implements XxGamMaApproverHierarchyLovVO {

    /**This is the default constructor (do not remove)
     */
    public XxGamMaApproverHierarchyLovVOImpl() {
    }

    /**
     * Asigna valores a los parametros de busqueda para aprobadores de jerarquia RH
     * @param jobNameId contiene el id del puesto de trabajo del empleado
     * @param versionId contiene el id de la version de jerarquia del empleado
     */
    public void setSearchApproverHierarchy(Number jobNameId, 
                                           Number versionId) {

        if (jobNameId != null && versionId != null) {
            setWhereClause(null);
            setWhereClauseParams(null);

            setpJobNameId(jobNameId);
            setpVersion(versionId);

            executeQuery();
        }
    }


    public void executeQuery() {
        setWhereClause(null);
        setWhereClauseParams(null);
        super.executeQuery();
    }


    /**Gets the bind variable value for pVersion
     */
    public Number getpVersion() {
        return (Number)getNamedWhereClauseParam("pVersion");
    }

    /**Sets <code>value</code> for bind variable pVersion
     */
    public void setpVersion(Number value) {
        setNamedWhereClauseParam("pVersion", value);
    }


    /**Gets the bind variable value for pJobNameId
     */
    public Number getpJobNameId() {
        return (Number)getNamedWhereClauseParam("pJobNameId");
    }

    /**Sets <code>value</code> for bind variable pJobNameId
     */
    public void setpJobNameId(Number value) {
        setNamedWhereClauseParam("pJobNameId", value);
    }
}
