package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.domain.Number;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTemplatePaymentFlexLovVOImpl extends OAViewObjectImpl {

    /**
     * Contiene el id de la plantilla de anticipo para centro de costo alterno
     */
    private Number templateId;

    /**
     * Contiene el valor del centro de costo alterno
     */
    private String costCenterFlex;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaTemplatePaymentFlexLovVOImpl() {
    }

    /**
     * Ejecuta la busqueda por el valor del centro de costo alterno
     * @param templateId contiene el id de la plantilla de anticipo
     * @param costCenterFlex contiene el valor del centro de costo alterno
     */
    public void searchTemplatePaymentByFlex(Number templateId, 
                                            String costCenterFlex) {
        if (costCenterFlex != null || templateId != null) {
            String ccost[] = costCenterFlex.split("-");
            if (ccost.length == 2)
                costCenterFlex = ccost[0];
            setTemplateId(templateId);
            setCostCenterFlex(costCenterFlex);
            executeQuery();
        }
    }

    /**
     * Configura los criterios de busqueda para la plantilla de anticipo
     * @param templateId contiene el id de la plantilla de anticipo
     * @param costCenterFlex contiene el valor del centro de costo alterno
     */
    public void setSearchTemplatePaymentByFlexVc(Number templateId, 
                                                 String costCenterFlex) {

        //Declaración de los recursos
        ViewCriteria vc = null;
        ViewCriteriaRow vcRow = null;

        //Crea el view criteria
        vc = createViewCriteria();
        vcRow = vc.createViewCriteriaRow();

        if (costCenterFlex != null) {
            vcRow.setAttribute("CostCenterFlex", costCenterFlex);
        }
        if (templateId != null) {
            vcRow.setAttribute("TemplateId", costCenterFlex);
        }

        try {
            //Inicializa el criteria y lo aplica
            vc.addElement(vcRow);
            applyViewCriteria(vc);
        } catch (Exception exception) {
            //Propaga la excepcion
            clearViewCriterias();
        }
    }

    public void setTemplateId(Number templateId) {
        this.templateId = templateId;
    }

    public Number getTemplateId() {
        return templateId;
    }

    public void setCostCenterFlex(String costCenterFlex) {
        this.costCenterFlex = costCenterFlex;
    }

    public String getCostCenterFlex() {
        return costCenterFlex;
    }

    /***************
    public void executeQuery() {

        if(getCostCenterFlex() != null){
            setSearchTemplatePaymentByFlexVc(getTemplateId(), getCostCenterFlex());
            super.executeQuery();
            clearViewCriterias();
        }
    }
  ************************/

    /*******Procedimiento que se creo para que la lista de valores de modo Flex
     *******de las plantillas esten filtradas por organizacion reutilizando Codigo
     ***************/
    public

    void searchTemplatePaymentByFlex(Number templateId, String costCenterFlex, 
                                     String orgShortNameEmp) {

        System.out.println("Comienza searchTemplatePaymentByFlex 3 parametros Capa Lov Impl orgShortNameEmp:" + 
                           orgShortNameEmp);
        String costCenterLoc = null;
        if (costCenterFlex != null) {
            String ccost[] = costCenterFlex.split("-");
            if (ccost.length == 2)
                try {
                    costCenterFlex = ccost[0];
                    costCenterLoc = ccost[1];
                } catch (Exception e) {
                    System.out.println("Error al seteo de valores: " + 
                                       e.getMessage().toString());
                }
        }
        System.out.println("costCenterFlex: " + costCenterFlex);
        System.out.println("costCenterLoc: " + costCenterLoc);
        /**************************************************
     * causa de muchos errores
    setWhereClause(null);
    setWhereClauseParams(null);
    setWhereClause("COST_CENTER_FLEX = :CostCenterFlex");
    defineNamedWhereClauseParam("CostCenterFlex", null, null);
    defineNamedWhereClauseParam("shortOrgName", null, null);
    setshortOrgName(orgShortNameEmp);
    setNamedWhereClauseParam("CostCenterFlex",costCenterFlex);
    super.executeQuery();
    clearViewCriterias();
    ******************************************************/

        ViewCriteria vc = null;
        ViewCriteriaRow vcRow = null;
        // 2. Create a view criteria row set for this view object
        vc = createViewCriteria();
        // 3. Use the view criteria to create one or more view criteria rows
        vcRow = vc.createViewCriteriaRow();
        // 4. Set attribute values to filter on in appropriate view criteria rows
        if (null != costCenterFlex) {
            vcRow.setAttribute("CostCenterFlex", costCenterFlex);
        }
        if (null != templateId) {
            vcRow.setAttribute("TemplateId", templateId);
        }

        if (null != orgShortNameEmp) {
            vcRow.setAttribute("UnidadOperativa", orgShortNameEmp + "%");
        }

        if (null != costCenterLoc && !"".equals(costCenterLoc)) {
            vcRow.setAttribute("TemplateDesc", "%" + costCenterLoc + "%");
        }

        try {
            // 5. Add the view criteria rows to the view critera row set
            vc.addElement(vcRow);
            // 6. Apply the view criteria to the view object
            applyViewCriteria(vc);
        } catch (Exception exception) {
            clearViewCriterias();
        }

        // 7. Execute the query
        executeQuery();
        while (hasNext()) {
            Row curPerson = next();
            System.out.println(curPerson.getAttribute("CostCenterFlex") + " " + 
                               curPerson.getAttribute("TemplateId") + " " + 
                               curPerson.getAttribute("UnidadOperativa"));
        }
        //clearViewCriterias();  


        System.out.println("Finaliza searchTemplatePaymentByFlex 3 parametros Capa Lov Impl");

        //**Example 5-23 Correct Use of setWhereClause() Method and Bind Variable
        /**Referecnias http://docs.oracle.com/cd/E17904_01/web.1111/b31974/bcquerying.htm#ADFFD305 **/
        /*** searchTemplatePaymentByFlex(Number templateId , String costCenterFlex) **/
    }

}
