package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaTypePaymentLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTypePaymentLovVOImpl extends OAViewObjectImpl implements XxGamMaTypePaymentLovVO {

    /**
     * Contiene el id de la plantilla de anticipo
     */
    private Number templateId;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaTypePaymentLovVOImpl() {
    }

    /**
     * Busca los tipos de anticipo por id de la plantilla de anticipo
     * @param templateId contiene el id de la plantilla de anticipo
     */
    public void searchTypePaymentByTemplateId(Number templateId) {
        if (templateId != null) {
            setTemplateId(templateId);
            executeQuery();
        }
    }

    public void executeQuery() {

        Number templateId = null;
        templateId = getTemplateId();
        if (templateId != null) {

            searchTypePaymentVc(templateId);

            super.executeQuery();
            clearViewCriterias();
        }
    }

    /**
     * Crea e implementa un view criteria para buscar por id de plantilla
     * de anticipo
     * @param templateId contiene id de plantilla de anticipo
     */
    public void searchTypePaymentVc(Number templateId) {

        if (templateId != null) {
            //Declaración de los recursos
            ViewCriteria vcLookup = null;
            ViewCriteriaRow vcLookupRow = null;

            //Crea el view criteria
            vcLookup = createViewCriteria();
            vcLookupRow = vcLookup.createViewCriteriaRow();

            //Inicializa el tipo de lookup
            vcLookupRow.setAttribute("TemplatePayment", templateId);

            try {
                //Inicializa el criteria y lo aplica
                vcLookup.addElement(vcLookupRow);
                applyViewCriteria(vcLookup);
            } catch (Exception exception) {
                //Propaga la excepcion
                exception.printStackTrace();
            }
        }
    }

    public void setTemplateId(Number templateId) {
        this.templateId = templateId;
    }

    public Number getTemplateId() {
        return templateId;
    }
}
