package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaCurrencyConversionLovVORowImpl extends OAViewRowImpl {
    public static final int FROMCURRENCY = 0;
    public static final int TOCURRENCY = 1;
    public static final int CONVERSIONDATE = 2;
    public static final int CONVERSIONRATE = 3;
    public static final int STATUSCODE = 4;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaCurrencyConversionLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute FromCurrency
     */
    public String getFromCurrency() {
        return (String)getAttributeInternal(FROMCURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FromCurrency
     */
    public void setFromCurrency(String value) {
        setAttributeInternal(FROMCURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute ToCurrency
     */
    public String getToCurrency() {
        return (String)getAttributeInternal(TOCURRENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ToCurrency
     */
    public void setToCurrency(String value) {
        setAttributeInternal(TOCURRENCY, value);
    }

    /**Gets the attribute value for the calculated attribute ConversionDate
     */
    public Date getConversionDate() {
        return (Date)getAttributeInternal(CONVERSIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConversionDate
     */
    public void setConversionDate(Date value) {
        setAttributeInternal(CONVERSIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute ConversionRate
     */
    public Number getConversionRate() {
        return (Number)getAttributeInternal(CONVERSIONRATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConversionRate
     */
    public void setConversionRate(Number value) {
        setAttributeInternal(CONVERSIONRATE, value);
    }

    /**Gets the attribute value for the calculated attribute StatusCode
     */
    public String getStatusCode() {
        return (String)getAttributeInternal(STATUSCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusCode
     */
    public void setStatusCode(String value) {
        setAttributeInternal(STATUSCODE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case FROMCURRENCY:
            return getFromCurrency();
        case TOCURRENCY:
            return getToCurrency();
        case CONVERSIONDATE:
            return getConversionDate();
        case CONVERSIONRATE:
            return getConversionRate();
        case STATUSCODE:
            return getStatusCode();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
