package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaPersonDataLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaPersonDataLovVOImpl extends OAViewObjectImpl implements XxGamMaPersonDataLovVO {
    /**This is the default constructor (do not remove)
     */
    public XxGamMaPersonDataLovVOImpl() {
    }

    /**
     * Busca los datos de la persona por id de persona
     * @param personId contiene el id de persona
     */
    public void searchPersonDataById(Number personId) {
        if (personId != null) {
            setWhereClause("person_id = :1");
            setWhereClauseParams(null);
            setWhereClauseParam(0, personId);
            executeQuery();
        }
    }
}
