package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaLimitScheduleOptionVORowImpl extends OAViewRowImpl
{
  public static final int FLEXCONCACTENATED = 0;
  public static final int RATE = 1;
  public static final int PROMPT = 2;
  public static final int PARAMETERID = 3;
  public static final int EXPENSEREPORTID = 4;
  public static final int CURRENCYCODE = 5;

  /**This is the default constructor (do not remove)
   */
  public XxGamMaLimitScheduleOptionVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute FlexConcactenated
   */
  public String getFlexConcactenated()
  {
    return (String) getAttributeInternal(FLEXCONCACTENATED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FlexConcactenated
   */
  public void setFlexConcactenated(String value)
  {
    setAttributeInternal(FLEXCONCACTENATED, value);
  }

  /**Gets the attribute value for the calculated attribute Rate
   */
  public Number getRate()
  {
    return (Number) getAttributeInternal(RATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Rate
   */
  public void setRate(Number value)
  {
    setAttributeInternal(RATE, value);
  }

  /**Gets the attribute value for the calculated attribute Prompt
   */
  public String getPrompt()
  {
    return (String) getAttributeInternal(PROMPT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Prompt
   */
  public void setPrompt(String value)
  {
    setAttributeInternal(PROMPT, value);
  }

  /**Gets the attribute value for the calculated attribute ParameterId
   */
  public Number getParameterId()
  {
    return (Number) getAttributeInternal(PARAMETERID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ParameterId
   */
  public void setParameterId(Number value)
  {
    setAttributeInternal(PARAMETERID, value);
  }

  /**Gets the attribute value for the calculated attribute ExpenseReportId
   */
  public Number getExpenseReportId()
  {
    return (Number) getAttributeInternal(EXPENSEREPORTID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ExpenseReportId
   */
  public void setExpenseReportId(Number value)
  {
    setAttributeInternal(EXPENSEREPORTID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case FLEXCONCACTENATED:
      return getFlexConcactenated();
    case RATE:
      return getRate();
    case PROMPT:
      return getPrompt();
    case PARAMETERID:
      return getParameterId();
    case EXPENSEREPORTID:
      return getExpenseReportId();
    case CURRENCYCODE:
      return getCurrencyCode();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case CURRENCYCODE:
      setCurrencyCode((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for the calculated attribute CurrencyCode
   */
  public String getCurrencyCode()
  {
    return (String) getAttributeInternal(CURRENCYCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
   */
  public void setCurrencyCode(String value)
  {
    setAttributeInternal(CURRENCYCODE, value);
  }
}
