package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTypePaymentLovVORowImpl extends OAViewRowImpl {
    public static final int TYPEPAYMENTID = 0;
    public static final int TEMPLATEPAYMENT = 1;
    public static final int FLEXCONCACTENATED = 2;
    public static final int TYPEPAYMENTDESC = 3;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaTypePaymentLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute TypePaymentId
     */
    public Number getTypePaymentId() {
        return (Number) getAttributeInternal(TYPEPAYMENTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypePaymentId
     */
    public void setTypePaymentId(Number value) {
        setAttributeInternal(TYPEPAYMENTID, value);
    }

    /**Gets the attribute value for the calculated attribute TemplatePayment
     */
    public Number getTemplatePayment() {
        return (Number) getAttributeInternal(TEMPLATEPAYMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TemplatePayment
     */
    public void setTemplatePayment(Number value) {
        setAttributeInternal(TEMPLATEPAYMENT, value);
    }

    /**Gets the attribute value for the calculated attribute FlexConcactenated
     */
    public String getFlexConcactenated() {
        return (String) getAttributeInternal(FLEXCONCACTENATED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FlexConcactenated
     */
    public void setFlexConcactenated(String value) {
        setAttributeInternal(FLEXCONCACTENATED, value);
    }

    /**Gets the attribute value for the calculated attribute TypePaymentDesc
     */
    public String getTypePaymentDesc() {
        return (String) getAttributeInternal(TYPEPAYMENTDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypePaymentDesc
     */
    public void setTypePaymentDesc(String value) {
        setAttributeInternal(TYPEPAYMENTDESC, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TYPEPAYMENTID:
            return getTypePaymentId();
        case TEMPLATEPAYMENT:
            return getTemplatePayment();
        case FLEXCONCACTENATED:
            return getFlexConcactenated();
        case TYPEPAYMENTDESC:
            return getTypePaymentDesc();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


}
