package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaResponsibilityAppLovVORowImpl extends OAViewRowImpl {
    public static final int RESPONSIBILITYID = 0;
    public static final int RESPONSIBILITYKEY = 1;
    public static final int APPLICATIONID = 2;
    public static final int APPLICATIONSHORTNAME = 3;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaResponsibilityAppLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute ResponsibilityId
     */
    public Number getResponsibilityId() {
        return (Number) getAttributeInternal(RESPONSIBILITYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ResponsibilityId
     */
    public void setResponsibilityId(Number value) {
        setAttributeInternal(RESPONSIBILITYID, value);
    }

    /**Gets the attribute value for the calculated attribute ResponsibilityKey
     */
    public String getResponsibilityKey() {
        return (String) getAttributeInternal(RESPONSIBILITYKEY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ResponsibilityKey
     */
    public void setResponsibilityKey(String value) {
        setAttributeInternal(RESPONSIBILITYKEY, value);
    }

    /**Gets the attribute value for the calculated attribute ApplicationId
     */
    public Number getApplicationId() {
        return (Number) getAttributeInternal(APPLICATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApplicationId
     */
    public void setApplicationId(Number value) {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute ApplicationShortName
     */
    public String getApplicationShortName() {
        return (String) getAttributeInternal(APPLICATIONSHORTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApplicationShortName
     */
    public void setApplicationShortName(String value) {
        setAttributeInternal(APPLICATIONSHORTNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RESPONSIBILITYID:
            return getResponsibilityId();
        case RESPONSIBILITYKEY:
            return getResponsibilityKey();
        case APPLICATIONID:
            return getApplicationId();
        case APPLICATIONSHORTNAME:
            return getApplicationShortName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
