package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaCostCenterFlexLovVOImpl extends OAViewObjectImpl {

    /**
     * Contiene el valor del centro de costo alterno
     */
    private String costCenterFlex;

    /**
     * Contiene el lookup type de tarjeta virtual
     */
    private String vcLookupType;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaCostCenterFlexLovVOImpl() {
    }
    
    /**
     * Ejecuta la consulta para buscar centro de costo alterno
     * @param costCenterFlex contiene el valor del centro de costo alterno
     * @param vcLookupType contiene el lookup type para tarjeta virtual
     */
    public void searchCostCenterFlex(String costCenterFlex, String vcLookupType){
    
        if(vcLookupType != null){
            setVcLookupType(vcLookupType);
            setCostCenterFlex(costCenterFlex);
            executeQuery();
        }
    }
    
    /**
     * Crea un view criteria para buscar centro de costo alterno
     * @param vcLookupType contiene el lookup type de tarjeta virtual
     * @param costCenterFlex contiene el valor del centro de costo alterno
     */
    public void setCostCenterFlexVC(String vcLookupType, String costCenterFlex){
        
        if(vcLookupType != null){
            
            //Declaración de los recursos
            ViewCriteria vcLookup = null;
            ViewCriteriaRow vcLookupRow = null;

            //Crea el view criteria
            vcLookup = createViewCriteria();
            vcLookupRow = vcLookup.createViewCriteriaRow();
            
            //Inicializa el tipo de lookup
            vcLookupRow.setAttribute("VcLookupType", vcLookupType);
            //vcLookupRow.setAttribute("RN", '1');// Only for test
            //Inicializa el cost center
            if (costCenterFlex != null )
                vcLookupRow.setAttribute("CostCenterFlex", costCenterFlex);
            try {
                //Inicializa el criteria y lo aplica
                vcLookup.addElement(vcLookupRow);
                applyViewCriteria(vcLookup);
            } catch (Exception exception) {
                //Propaga la excepcion
                exception.printStackTrace();
            }
        }
    }

    public void setCostCenterFlex(String costCenterFlex) {
        this.costCenterFlex = costCenterFlex;
    }

    public String getCostCenterFlex() {
        return costCenterFlex;
    }

    public void setVcLookupType(String vcLookupType) {
        this.vcLookupType = vcLookupType;
    }

    public String getVcLookupType() {
        return vcLookupType;
    }

    public void executeQuery() {
        
        if(getVcLookupType() != null){
            setCostCenterFlexVC(getVcLookupType(), getCostCenterFlex());
        }
        super.executeQuery();
        clearViewCriterias();
    }
}
