package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaSupervisorLovVORowImpl extends OAViewRowImpl {
    public static final int PERSONID = 0;
    public static final int FULLNAME = 1;
    public static final int FIRSTNAME = 2;
    public static final int LASTNAME = 3;
    public static final int EMAILADDRESS = 4;
    public static final int SEX = 5;
    public static final int SUPERVISORID = 6;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaSupervisorLovVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number)getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for the calculated attribute FullName
     */
    public String getFullName() {
        return (String)getAttributeInternal(FULLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute FirstName
     */
    public String getFirstName() {
        return (String)getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute LastName
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for the calculated attribute EmailAddress
     */
    public String getEmailAddress() {
        return (String)getAttributeInternal(EMAILADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmailAddress
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**Gets the attribute value for the calculated attribute Sex
     */
    public String getSex() {
        return (String)getAttributeInternal(SEX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sex
     */
    public void setSex(String value) {
        setAttributeInternal(SEX, value);
    }

    /**Gets the attribute value for the calculated attribute SupervisorId
     */
    public Number getSupervisorId() {
        return (Number)getAttributeInternal(SUPERVISORID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SupervisorId
     */
    public void setSupervisorId(Number value) {
        setAttributeInternal(SUPERVISORID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PERSONID:
            return getPersonId();
        case FULLNAME:
            return getFullName();
        case FIRSTNAME:
            return getFirstName();
        case LASTNAME:
            return getLastName();
        case EMAILADDRESS:
            return getEmailAddress();
        case SEX:
            return getSex();
        case SUPERVISORID:
            return getSupervisorId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
