package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaApproverByEmployeeIdLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaApproverByEmployeeIdLovVOImpl extends OAViewObjectImpl implements XxGamMaApproverByEmployeeIdLovVO {
    /**This is the default constructor (do not remove)
     */
    public XxGamMaApproverByEmployeeIdLovVOImpl() {
    }

    /**
     * Ejecuta la consulta para buscar el aprobador por id del empleado
     * y centro de costos
     * @param numEmployeeId contiene id de empleado
     * @param codeCombinationId contiene el id del codigo de combinacion contable
     */
    public void searchApproverByCombinationEmployee(Number numEmployeeId, Number codeCombinationId){
        
        if(numEmployeeId != null && codeCombinationId != null){
            setWhereClause("employee_person_id = :1 and code_combination_id = :2");
            setWhereClauseParams(null);
            setWhereClauseParam(0, numEmployeeId);
            setWhereClauseParam(1, codeCombinationId);
            executeQuery();
        }
    }
}
