package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;

import xxgam.oracle.apps.xbol.maf.utils.XxGamConstantsUtil;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTicketRateLovVOImpl extends OAViewObjectImpl
{
  /**This is the default constructor (do not remove)
   */
  public XxGamMaTicketRateLovVOImpl()
  {
  }

  /**
   * Metodo para inicializar la lista de valores TicketRateLov
   */
  void initTicketRate(String franchiseType)
  {
  
    // 1. Declaracion de los recursos
    ViewCriteria vc = null;
    ViewCriteriaRow vcRow = null;
    // 2. Create a view criteria row set for this view object
      vc = createViewCriteria();
    // 3. Use the view criteria to create one or more view criteria rows
      vcRow = vc.createViewCriteriaRow();
    // 4. Set attribute values to filter on in appropriate view criteria rows
     if(null!=franchiseType&&!"".equals(franchiseType)){
       vcRow.setAttribute("Tag",XxGamConstantsUtil.LIKE_OPEN+franchiseType+XxGamConstantsUtil.LIKE_CLOSE);
     }  
     
    try
       {
         // 5. Add the view criteria rows to the view critera row set
         vc. addElement(vcRow);
         // 6. Apply the view criteria to the view object
         applyViewCriteria(vc);
       }
       catch (Exception exception) {
         clearViewCriterias();
      }
    
    // 7. Execute the query
    executeQuery();
    while (hasNext()) {
           Row curTicketRate = next();
           System.out.println(curTicketRate.getAttribute("Meaning") + " " +curTicketRate.getAttribute("Id")+" " +curTicketRate.getAttribute("Tag"));
           }
  
  }
  
}
