package xxgam.oracle.apps.xbol.maf.lov.server;

import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTypeEmissionLovVOImpl extends OAViewObjectImpl
{
    /**This is the default constructor (do not remove)
     */
    public XxGamMaTypeEmissionLovVOImpl() {
    }
    
    
    
    public String getTypeEmissionDescription(String lookUpCode){
        //Verifica nulidad
        String description = null;
        if (lookUpCode == null)
            return null;
        setTypeEmissionVc(lookUpCode);
        executeQuery();
        
        if (getRowCount() > 0) {
            description  = String.valueOf(first().getAttribute("Meaning"));
        }
        
        clearViewCriterias();
        return description;
    }
    
    public void setTypeEmissionVc(String lookupCode){
        
        if(lookupCode != null){
            //Declaración de los recursos
            ViewCriteria vcLookup = null;
            ViewCriteriaRow vcLookupRow = null;

            //Crea el view criteria
            vcLookup = createViewCriteria();
            vcLookupRow = vcLookup.createViewCriteriaRow();
            
            //Inicializa el tipo de lookup
            vcLookupRow.setAttribute("LookupCode", lookupCode);
            
            try {
                //Inicializa el criteria y lo aplica
                vcLookup.addElement(vcLookupRow);
                applyViewCriteria(vcLookup);
            } catch (Exception exception) {
                clearViewCriterias();
            }   
        }
    }
}
