package xxgam.oracle.apps.inv.moveorder.vta.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamInvVtaUnifHdrEOImpl extends OAEntityImpl
{
  public static final int HDRID = 0;
  public static final int PERSONID = 1;
  public static final int FULLNAME = 2;
  public static final int EMPLOYEENUMBER = 3;
  public static final int ASSIGMENTID = 4;
  public static final int OPERATINGUNITID = 5;
  public static final int HRORGID = 6;
  public static final int SOTRANSACTIONTYPEID = 7;
  public static final int SOLISTHDRID = 8;
  public static final int SOCUSTID = 9;
  public static final int SOSHIPID = 10;
  public static final int SOBILLID = 11;
  public static final int SOCURRENCYCODE = 12;
  public static final int SOHEADERID = 13;
  public static final int SOORDERNUMBER = 14;
  public static final int ATTRIBUTECATEGORY = 15;
  public static final int ATTRIBUTE1 = 16;
  public static final int ATTRIBUTE2 = 17;
  public static final int ATTRIBUTE3 = 18;
  public static final int ATTRIBUTE4 = 19;
  public static final int ATTRIBUTE5 = 20;
  public static final int ATTRIBUTE6 = 21;
  public static final int ATTRIBUTE7 = 22;
  public static final int ATTRIBUTE8 = 23;
  public static final int CREATEDBY = 24;
  public static final int CREATIONDATE = 25;
  public static final int LASTUPDATEDATE = 26;
  public static final int LASTUPDATEDBY = 27;
  public static final int LASTUPDATELOGIN = 28;
  public static final int XXGAMINVVTAUNIFLINEO = 29;


  private static OAEntityDefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public XxGamInvVtaUnifHdrEOImpl()
  {
  }


  /**Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = 
          (OAEntityDefImpl)EntityDefImpl.findDefObject("xxgam.oracle.apps.inv.moveorder.vta.schema.server.XxGamInvVtaUnifHdrEO");
    }
    return mDefinitionObject;
  }

  /**Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**Gets the attribute value for HdrId, using the alias name HdrId
   */
  public Number getHdrId()
  {
    return (Number)getAttributeInternal(HDRID);
  }

  /**Sets <code>value</code> as the attribute value for HdrId
   */
  public void setHdrId(Number value)
  {
    setAttributeInternal(HDRID, value);
  }

  /**Gets the attribute value for PersonId, using the alias name PersonId
   */
  public Number getPersonId()
  {
    return (Number)getAttributeInternal(PERSONID);
  }

  /**Sets <code>value</code> as the attribute value for PersonId
   */
  public void setPersonId(Number value)
  {
    setAttributeInternal(PERSONID, value);
  }

  /**Gets the attribute value for FullName, using the alias name FullName
   */
  public String getFullName()
  {
    return (String)getAttributeInternal(FULLNAME);
  }

  /**Sets <code>value</code> as the attribute value for FullName
   */
  public void setFullName(String value)
  {
    setAttributeInternal(FULLNAME, value);
  }

  /**Gets the attribute value for EmployeeNumber, using the alias name EmployeeNumber
   */
  public String getEmployeeNumber()
  {
    return (String)getAttributeInternal(EMPLOYEENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for EmployeeNumber
   */
  public void setEmployeeNumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**Gets the attribute value for AssigmentId, using the alias name AssigmentId
   */
  public Number getAssigmentId()
  {
    return (Number)getAttributeInternal(ASSIGMENTID);
  }

  /**Sets <code>value</code> as the attribute value for AssigmentId
   */
  public void setAssigmentId(Number value)
  {
    setAttributeInternal(ASSIGMENTID, value);
  }

  /**Gets the attribute value for OperatingUnitId, using the alias name OperatingUnitId
   */
  public Number getOperatingUnitId()
  {
    return (Number)getAttributeInternal(OPERATINGUNITID);
  }

  /**Sets <code>value</code> as the attribute value for OperatingUnitId
   */
  public void setOperatingUnitId(Number value)
  {
    setAttributeInternal(OPERATINGUNITID, value);
  }

  /**Gets the attribute value for HrOrgId, using the alias name HrOrgId
   */
  public Number getHrOrgId()
  {
    return (Number)getAttributeInternal(HRORGID);
  }

  /**Sets <code>value</code> as the attribute value for HrOrgId
   */
  public void setHrOrgId(Number value)
  {
    setAttributeInternal(HRORGID, value);
  }

  /**Gets the attribute value for SoTransactionTypeId, using the alias name SoTransactionTypeId
   */
  public Number getSoTransactionTypeId()
  {
    return (Number)getAttributeInternal(SOTRANSACTIONTYPEID);
  }

  /**Sets <code>value</code> as the attribute value for SoTransactionTypeId
   */
  public void setSoTransactionTypeId(Number value)
  {
    setAttributeInternal(SOTRANSACTIONTYPEID, value);
  }

  /**Gets the attribute value for SoListHdrId, using the alias name SoListHdrId
   */
  public Number getSoListHdrId()
  {
    return (Number)getAttributeInternal(SOLISTHDRID);
  }

  /**Sets <code>value</code> as the attribute value for SoListHdrId
   */
  public void setSoListHdrId(Number value)
  {
    setAttributeInternal(SOLISTHDRID, value);
  }

  /**Gets the attribute value for SoCustId, using the alias name SoCustId
   */
  public Number getSoCustId()
  {
    return (Number)getAttributeInternal(SOCUSTID);
  }

  /**Sets <code>value</code> as the attribute value for SoCustId
   */
  public void setSoCustId(Number value)
  {
    setAttributeInternal(SOCUSTID, value);
  }

  /**Gets the attribute value for SoShipId, using the alias name SoShipId
   */
  public Number getSoShipId()
  {
    return (Number)getAttributeInternal(SOSHIPID);
  }

  /**Sets <code>value</code> as the attribute value for SoShipId
   */
  public void setSoShipId(Number value)
  {
    setAttributeInternal(SOSHIPID, value);
  }

  /**Gets the attribute value for SoBillId, using the alias name SoBillId
   */
  public Number getSoBillId()
  {
    return (Number)getAttributeInternal(SOBILLID);
  }

  /**Sets <code>value</code> as the attribute value for SoBillId
   */
  public void setSoBillId(Number value)
  {
    setAttributeInternal(SOBILLID, value);
  }

  /**Gets the attribute value for SoCurrencyCode, using the alias name SoCurrencyCode
   */
  public String getSoCurrencyCode()
  {
    return (String)getAttributeInternal(SOCURRENCYCODE);
  }

  /**Sets <code>value</code> as the attribute value for SoCurrencyCode
   */
  public void setSoCurrencyCode(String value)
  {
    setAttributeInternal(SOCURRENCYCODE, value);
  }

  /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
   */
  public String getAttributeCategory()
  {
    return (String)getAttributeInternal(ATTRIBUTECATEGORY);
  }

  /**Sets <code>value</code> as the attribute value for AttributeCategory
   */
  public void setAttributeCategory(String value)
  {
    setAttributeInternal(ATTRIBUTECATEGORY, value);
  }

  /**Gets the attribute value for Attribute1, using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as the attribute value for Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for Attribute2, using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String)getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as the attribute value for Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for Attribute3, using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String)getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as the attribute value for Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for Attribute4, using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String)getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as the attribute value for Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for Attribute5, using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String)getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as the attribute value for Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**Gets the attribute value for Attribute6, using the alias name Attribute6
   */
  public String getAttribute6()
  {
    return (String)getAttributeInternal(ATTRIBUTE6);
  }

  /**Sets <code>value</code> as the attribute value for Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**Gets the attribute value for Attribute7, using the alias name Attribute7
   */
  public String getAttribute7()
  {
    return (String)getAttributeInternal(ATTRIBUTE7);
  }

  /**Sets <code>value</code> as the attribute value for Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**Gets the attribute value for Attribute8, using the alias name Attribute8
   */
  public String getAttribute8()
  {
    return (String)getAttributeInternal(ATTRIBUTE8);
  }

  /**Sets <code>value</code> as the attribute value for Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case HDRID:
      return getHdrId();
    case PERSONID:
      return getPersonId();
    case FULLNAME:
      return getFullName();
    case EMPLOYEENUMBER:
      return getEmployeeNumber();
    case ASSIGMENTID:
      return getAssigmentId();
    case OPERATINGUNITID:
      return getOperatingUnitId();
    case HRORGID:
      return getHrOrgId();
    case SOTRANSACTIONTYPEID:
      return getSoTransactionTypeId();
    case SOLISTHDRID:
      return getSoListHdrId();
    case SOCUSTID:
      return getSoCustId();
    case SOSHIPID:
      return getSoShipId();
    case SOBILLID:
      return getSoBillId();
    case SOCURRENCYCODE:
      return getSoCurrencyCode();
    case SOHEADERID:
      return getSoHeaderId();
    case SOORDERNUMBER:
      return getSoOrderNumber();
    case ATTRIBUTECATEGORY:
      return getAttributeCategory();
    case ATTRIBUTE1:
      return getAttribute1();
    case ATTRIBUTE2:
      return getAttribute2();
    case ATTRIBUTE3:
      return getAttribute3();
    case ATTRIBUTE4:
      return getAttribute4();
    case ATTRIBUTE5:
      return getAttribute5();
    case ATTRIBUTE6:
      return getAttribute6();
    case ATTRIBUTE7:
      return getAttribute7();
    case ATTRIBUTE8:
      return getAttribute8();
    case CREATEDBY:
      return getCreatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    case XXGAMINVVTAUNIFLINEO:
      return getXxGamInvVtaUnifLinEO();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case HDRID:
      setHdrId((Number)value);
      return;
    case PERSONID:
      setPersonId((Number)value);
      return;
    case FULLNAME:
      setFullName((String)value);
      return;
    case EMPLOYEENUMBER:
      setEmployeeNumber((String)value);
      return;
    case ASSIGMENTID:
      setAssigmentId((Number)value);
      return;
    case OPERATINGUNITID:
      setOperatingUnitId((Number)value);
      return;
    case HRORGID:
      setHrOrgId((Number)value);
      return;
    case SOTRANSACTIONTYPEID:
      setSoTransactionTypeId((Number)value);
      return;
    case SOLISTHDRID:
      setSoListHdrId((Number)value);
      return;
    case SOCUSTID:
      setSoCustId((Number)value);
      return;
    case SOSHIPID:
      setSoShipId((Number)value);
      return;
    case SOBILLID:
      setSoBillId((Number)value);
      return;
    case SOCURRENCYCODE:
      setSoCurrencyCode((String)value);
      return;
    case SOHEADERID:
      setSoHeaderId((Number)value);
      return;
    case SOORDERNUMBER:
      setSoOrderNumber((String)value);
      return;
    case ATTRIBUTECATEGORY:
      setAttributeCategory((String)value);
      return;
    case ATTRIBUTE1:
      setAttribute1((String)value);
      return;
    case ATTRIBUTE2:
      setAttribute2((String)value);
      return;
    case ATTRIBUTE3:
      setAttribute3((String)value);
      return;
    case ATTRIBUTE4:
      setAttribute4((String)value);
      return;
    case ATTRIBUTE5:
      setAttribute5((String)value);
      return;
    case ATTRIBUTE6:
      setAttribute6((String)value);
      return;
    case ATTRIBUTE7:
      setAttribute7((String)value);
      return;
    case ATTRIBUTE8:
      setAttribute8((String)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for SoHeaderId, using the alias name SoHeaderId
   */
  public Number getSoHeaderId()
  {
    return (Number)getAttributeInternal(SOHEADERID);
  }

  /**Sets <code>value</code> as the attribute value for SoHeaderId
   */
  public void setSoHeaderId(Number value)
  {
    setAttributeInternal(SOHEADERID, value);
  }

  /**Gets the attribute value for SoOrderNumber, using the alias name SoOrderNumber
   */
  public String getSoOrderNumber()
  {
    return (String)getAttributeInternal(SOORDERNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for SoOrderNumber
   */
  public void setSoOrderNumber(String value)
  {
    setAttributeInternal(SOORDERNUMBER, value);
  }

  /**Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getXxGamInvVtaUnifLinEO()
  {
    return (RowIterator)getAttributeInternal(XXGAMINVVTAUNIFLINEO);
  }

  /**Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number hdrId)
  {
    return new Key(new Object[]{hdrId});
  }
}
