package xxgam.oracle.apps.inv.moveorder.vta.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamUniformsLOVAMImpl extends OAApplicationModuleImpl
{
  /**This is the default constructor (do not remove)
   */
  public XxGamUniformsLOVAMImpl()
  {
  }

  /**Sample main for debugging Business Components code using the tester.
   */
  public static void main(String[] args)
  {
    launchTester("xxgam.oracle.apps.inv.moveorder.vta.lov.server", /* package name */
      "XxGamUniformsLOVAMLocal" /* Configuration Name */);
  }

  /**Container's getter for XxGamVtaUniformsPricesLOVVO1
   */
  public XxGamVtaUniformsPricesLOVVOImpl getXxGamVtaUniformsPricesLOVVO1()
  {
    return (XxGamVtaUniformsPricesLOVVOImpl)findViewObject("XxGamVtaUniformsPricesLOVVO1");
  }
  
  /**Container's getter for XxGamSoEmpleadosLOVVO1
   */
  public XxGamSoEmpleadosLOVVOImpl getXxGamSoEmpleadosLOVVO1()
  {
    return (XxGamSoEmpleadosLOVVOImpl)findViewObject("XxGamSoEmpleadosLOVVO1");
  }

  /**
   * Metodo que inicializa el view object XxGamVtaUniformsPricesLOVVO
   */
  public void initVtaUniformsPricesLOV(oracle.jbo.domain.Number pNumPriceListHdrID 
                                      ,oracle.jbo.domain.Number pNumDotaID)
  {
    XxGamVtaUniformsPricesLOVVOImpl VtaUniformsPricesLOVVOImpl = getXxGamVtaUniformsPricesLOVVO1(); 
    if(null!=VtaUniformsPricesLOVVOImpl){
      VtaUniformsPricesLOVVOImpl.initVtaUniformsPricesLOV(pNumPriceListHdrID,pNumDotaID);
    }
  }

  

  public void initVtaUniformsPricesLOVEmpty()
  {
    XxGamVtaUniformsPricesLOVVOImpl VtaUniformsPricesLOVVOImpl = getXxGamVtaUniformsPricesLOVVO1(); 
    if(null!=VtaUniformsPricesLOVVOImpl){
      VtaUniformsPricesLOVVOImpl.initVtaUniformsPricesEmpty();
    }
  }
  
}
