package xxgam.oracle.apps.inv.moveorder.vta.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamVtaUniformsPricesLOVVOImpl extends OAViewObjectImpl
{
  /**This is the default constructor (do not remove)
   */
  public XxGamVtaUniformsPricesLOVVOImpl()
  {
  }
   
  /**
   * Metodo que incializa el view object
   */
  void initVtaUniformsPricesLOV(oracle.jbo.domain.Number pNumPriceListHdrID
                                ,oracle.jbo.domain.Number pNumDotaID)
  {
    this.setMaxFetchSize(-1);
    Number numListHeaderId = pNumPriceListHdrID; /** new Number(6014); **/
    Number numDotaId =pNumDotaID;
    
    /* 2. Create a view criteria row set for this view object  */
    ViewCriteria vc = this.createViewCriteria(); 
    /* 3. Use the view criteria to create one or more view criteria rows */ 
    ViewCriteriaRow vcr1 = vc.createViewCriteriaRow();
    /* 4. Set attribute values to filter on in appropriate view criteria rows */
    if(null!=numListHeaderId){
     vcr1.setAttribute("ListHeaderId",numListHeaderId); 
    }
    if(null!=numDotaId){
      vcr1.setAttribute("DotaId",numDotaId);
    }
     
     vc.add(vcr1); 
    this.applyViewCriteria(vc);
    /*************************************************************************
    this.setWhereClause(" dota_id = '12'  AND talla_nbr LIKE '"  + "" + "%'");
    ****************************************************************************/
    this.executeQuery();
   
    while(this.hasNext()){
     this.next();
    }
   
    
  }

  /**
   * Metodo que provoca que no desplege informacion
   */
  void initVtaUniformsPricesEmpty()
  {
  this.setMaxFetchSize(0);
  this.executeQuery();
  }
  
}
