package xxgam.oracle.apps.inv.moveorder.vta.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxgam.oracle.apps.inv.moveorder.vta.schema.server.XxGamInvVtaUnifHdrEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamInvVtaUnifHdrVORowImpl extends OAViewRowImpl
{
  public static final int HDRID = 0;
  public static final int PERSONID = 1;
  public static final int FULLNAME = 2;
  public static final int EMPLOYEENUMBER = 3;
  public static final int ASSIGMENTID = 4;
  public static final int OPERATINGUNITID = 5;
  public static final int HRORGID = 6;
  public static final int SOTRANSACTIONTYPEID = 7;
  public static final int SOLISTHDRID = 8;
  public static final int SOCUSTID = 9;
  public static final int SOSHIPID = 10;
  public static final int SOBILLID = 11;
  public static final int SOCURRENCYCODE = 12;
  public static final int ATTRIBUTECATEGORY = 13;
  public static final int ATTRIBUTE1 = 14;
  public static final int ATTRIBUTE2 = 15;
  public static final int ATTRIBUTE3 = 16;
  public static final int ATTRIBUTE4 = 17;
  public static final int ATTRIBUTE5 = 18;
  public static final int ATTRIBUTE6 = 19;
  public static final int ATTRIBUTE7 = 20;
  public static final int ATTRIBUTE8 = 21;
  public static final int CREATEDBY = 22;
  public static final int CREATIONDATE = 23;
  public static final int LASTUPDATEDATE = 24;
  public static final int LASTUPDATEDBY = 25;
  public static final int LASTUPDATELOGIN = 26;

  /**This is the default constructor (do not remove)
   */
  public XxGamInvVtaUnifHdrVORowImpl()
  {
  }

  /**Gets XxGamInvVtaUnifHdrEO entity object.
   */
  public XxGamInvVtaUnifHdrEOImpl getXxGamInvVtaUnifHdrEO()
  {
    return (XxGamInvVtaUnifHdrEOImpl)getEntity(0);
  }

  /**Gets the attribute value for HDR_ID using the alias name HdrId
   */
  public Number getHdrId()
  {
    return (Number) getAttributeInternal(HDRID);
  }

  /**Sets <code>value</code> as attribute value for HDR_ID using the alias name HdrId
   */
  public void setHdrId(Number value)
  {
    setAttributeInternal(HDRID, value);
  }

  /**Gets the attribute value for PERSON_ID using the alias name PersonId
   */
  public Number getPersonId()
  {
    return (Number) getAttributeInternal(PERSONID);
  }

  /**Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId
   */
  public void setPersonId(Number value)
  {
    setAttributeInternal(PERSONID, value);
  }

  /**Gets the attribute value for FULL_NAME using the alias name FullName
   */
  public String getFullName()
  {
    return (String) getAttributeInternal(FULLNAME);
  }

  /**Sets <code>value</code> as attribute value for FULL_NAME using the alias name FullName
   */
  public void setFullName(String value)
  {
    setAttributeInternal(FULLNAME, value);
  }

  /**Gets the attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber
   */
  public String getEmployeeNumber()
  {
    return (String) getAttributeInternal(EMPLOYEENUMBER);
  }

  /**Sets <code>value</code> as attribute value for EMPLOYEE_NUMBER using the alias name EmployeeNumber
   */
  public void setEmployeeNumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**Gets the attribute value for ASSIGMENT_ID using the alias name AssigmentId
   */
  public Number getAssigmentId()
  {
    return (Number) getAttributeInternal(ASSIGMENTID);
  }

  /**Sets <code>value</code> as attribute value for ASSIGMENT_ID using the alias name AssigmentId
   */
  public void setAssigmentId(Number value)
  {
    setAttributeInternal(ASSIGMENTID, value);
  }

  /**Gets the attribute value for OPERATING_UNIT_ID using the alias name OperatingUnitId
   */
  public Number getOperatingUnitId()
  {
    return (Number) getAttributeInternal(OPERATINGUNITID);
  }

  /**Sets <code>value</code> as attribute value for OPERATING_UNIT_ID using the alias name OperatingUnitId
   */
  public void setOperatingUnitId(Number value)
  {
    setAttributeInternal(OPERATINGUNITID, value);
  }

  /**Gets the attribute value for HR_ORG_ID using the alias name HrOrgId
   */
  public Number getHrOrgId()
  {
    return (Number) getAttributeInternal(HRORGID);
  }

  /**Sets <code>value</code> as attribute value for HR_ORG_ID using the alias name HrOrgId
   */
  public void setHrOrgId(Number value)
  {
    setAttributeInternal(HRORGID, value);
  }

  /**Gets the attribute value for SO_TRANSACTION_TYPE_ID using the alias name SoTransactionTypeId
   */
  public Number getSoTransactionTypeId()
  {
    return (Number) getAttributeInternal(SOTRANSACTIONTYPEID);
  }

  /**Sets <code>value</code> as attribute value for SO_TRANSACTION_TYPE_ID using the alias name SoTransactionTypeId
   */
  public void setSoTransactionTypeId(Number value)
  {
    setAttributeInternal(SOTRANSACTIONTYPEID, value);
  }

  /**Gets the attribute value for SO_LIST_HDR_ID using the alias name SoListHdrId
   */
  public Number getSoListHdrId()
  {
    return (Number) getAttributeInternal(SOLISTHDRID);
  }

  /**Sets <code>value</code> as attribute value for SO_LIST_HDR_ID using the alias name SoListHdrId
   */
  public void setSoListHdrId(Number value)
  {
    setAttributeInternal(SOLISTHDRID, value);
  }

  /**Gets the attribute value for SO_CUST_ID using the alias name SoCustId
   */
  public Number getSoCustId()
  {
    return (Number) getAttributeInternal(SOCUSTID);
  }

  /**Sets <code>value</code> as attribute value for SO_CUST_ID using the alias name SoCustId
   */
  public void setSoCustId(Number value)
  {
    setAttributeInternal(SOCUSTID, value);
  }

  /**Gets the attribute value for SO_SHIP_ID using the alias name SoShipId
   */
  public Number getSoShipId()
  {
    return (Number) getAttributeInternal(SOSHIPID);
  }

  /**Sets <code>value</code> as attribute value for SO_SHIP_ID using the alias name SoShipId
   */
  public void setSoShipId(Number value)
  {
    setAttributeInternal(SOSHIPID, value);
  }

  /**Gets the attribute value for SO_BILL_ID using the alias name SoBillId
   */
  public Number getSoBillId()
  {
    return (Number) getAttributeInternal(SOBILLID);
  }

  /**Sets <code>value</code> as attribute value for SO_BILL_ID using the alias name SoBillId
   */
  public void setSoBillId(Number value)
  {
    setAttributeInternal(SOBILLID, value);
  }

  /**Gets the attribute value for SO_CURRENCY_CODE using the alias name SoCurrencyCode
   */
  public String getSoCurrencyCode()
  {
    return (String) getAttributeInternal(SOCURRENCYCODE);
  }

  /**Sets <code>value</code> as attribute value for SO_CURRENCY_CODE using the alias name SoCurrencyCode
   */
  public void setSoCurrencyCode(String value)
  {
    setAttributeInternal(SOCURRENCYCODE, value);
  }

  /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
   */
  public String getAttributeCategory()
  {
    return (String) getAttributeInternal(ATTRIBUTECATEGORY);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
   */
  public void setAttributeCategory(String value)
  {
    setAttributeInternal(ATTRIBUTECATEGORY, value);
  }

  /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String) getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String) getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String) getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String) getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String) getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
   */
  public String getAttribute6()
  {
    return (String) getAttributeInternal(ATTRIBUTE6);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
   */
  public void setAttribute6(String value)
  {
    setAttributeInternal(ATTRIBUTE6, value);
  }

  /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
   */
  public String getAttribute7()
  {
    return (String) getAttributeInternal(ATTRIBUTE7);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
   */
  public void setAttribute7(String value)
  {
    setAttributeInternal(ATTRIBUTE7, value);
  }

  /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
   */
  public String getAttribute8()
  {
    return (String) getAttributeInternal(ATTRIBUTE8);
  }

  /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
   */
  public void setAttribute8(String value)
  {
    setAttributeInternal(ATTRIBUTE8, value);
  }

  /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number) getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date) getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number) getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number) getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case HDRID:
      return getHdrId();
    case PERSONID:
      return getPersonId();
    case FULLNAME:
      return getFullName();
    case EMPLOYEENUMBER:
      return getEmployeeNumber();
    case ASSIGMENTID:
      return getAssigmentId();
    case OPERATINGUNITID:
      return getOperatingUnitId();
    case HRORGID:
      return getHrOrgId();
    case SOTRANSACTIONTYPEID:
      return getSoTransactionTypeId();
    case SOLISTHDRID:
      return getSoListHdrId();
    case SOCUSTID:
      return getSoCustId();
    case SOSHIPID:
      return getSoShipId();
    case SOBILLID:
      return getSoBillId();
    case SOCURRENCYCODE:
      return getSoCurrencyCode();
    case ATTRIBUTECATEGORY:
      return getAttributeCategory();
    case ATTRIBUTE1:
      return getAttribute1();
    case ATTRIBUTE2:
      return getAttribute2();
    case ATTRIBUTE3:
      return getAttribute3();
    case ATTRIBUTE4:
      return getAttribute4();
    case ATTRIBUTE5:
      return getAttribute5();
    case ATTRIBUTE6:
      return getAttribute6();
    case ATTRIBUTE7:
      return getAttribute7();
    case ATTRIBUTE8:
      return getAttribute8();
    case CREATEDBY:
      return getCreatedBy();
    case CREATIONDATE:
      return getCreationDate();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case HDRID:
      setHdrId((Number)value);
      return;
    case PERSONID:
      setPersonId((Number)value);
      return;
    case FULLNAME:
      setFullName((String)value);
      return;
    case EMPLOYEENUMBER:
      setEmployeeNumber((String)value);
      return;
    case ASSIGMENTID:
      setAssigmentId((Number)value);
      return;
    case OPERATINGUNITID:
      setOperatingUnitId((Number)value);
      return;
    case HRORGID:
      setHrOrgId((Number)value);
      return;
    case SOTRANSACTIONTYPEID:
      setSoTransactionTypeId((Number)value);
      return;
    case SOLISTHDRID:
      setSoListHdrId((Number)value);
      return;
    case SOCUSTID:
      setSoCustId((Number)value);
      return;
    case SOSHIPID:
      setSoShipId((Number)value);
      return;
    case SOBILLID:
      setSoBillId((Number)value);
      return;
    case SOCURRENCYCODE:
      setSoCurrencyCode((String)value);
      return;
    case ATTRIBUTECATEGORY:
      setAttributeCategory((String)value);
      return;
    case ATTRIBUTE1:
      setAttribute1((String)value);
      return;
    case ATTRIBUTE2:
      setAttribute2((String)value);
      return;
    case ATTRIBUTE3:
      setAttribute3((String)value);
      return;
    case ATTRIBUTE4:
      setAttribute4((String)value);
      return;
    case ATTRIBUTE5:
      setAttribute5((String)value);
      return;
    case ATTRIBUTE6:
      setAttribute6((String)value);
      return;
    case ATTRIBUTE7:
      setAttribute7((String)value);
      return;
    case ATTRIBUTE8:
      setAttribute8((String)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }
}
