package xxgam.oracle.apps.inv.moveorder.vta.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamFollOrderUnifLinVOImpl extends OAViewObjectImpl
{
  /**This is the default constructor (do not remove)
   */
  public XxGamFollOrderUnifLinVOImpl()
  {
  }


  /**Gets the bind variable value for pSoHeaderID
   */
  public Number getpSoHeaderID()
  {
    return (Number)getNamedWhereClauseParam("pSoHeaderID");
  }

  /**Sets <code>value</code> for bind variable pSoHeaderID
   */
  public void setpSoHeaderID(Number value)
  {
    setNamedWhereClauseParam("pSoHeaderID", value);
  }
}
