package xxgam.oracle.apps.inv.moveorder.vta.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamPersonVtaUniformInfoVORowImpl extends OAViewRowImpl
{
  public static final int USERID = 0;
  public static final int PERSONID = 1;
  public static final int PERSONFULLNAME = 2;
  public static final int EMPLOYEENUMBER = 3;
  public static final int PERSONTYPE = 4;
  public static final int PERSONTYPEID = 5;
  public static final int SEX = 6;
  public static final int ASSIGMENTID = 7;
  public static final int ORGANIZATION = 8;
  public static final int ORGANIZATIONID = 9;
  public static final int GRADE = 10;
  public static final int GRADEID = 11;
  public static final int POSITION = 12;
  public static final int POSITIONID = 13;
  public static final int PAYROLL = 14;
  public static final int PAYROLLID = 15;
  public static final int STATION = 16;
  public static final int ACCOUNTCOMBINATION = 17;
  public static final int CODECOMBINATIONID = 18;
  public static final int OPERATINGUNIT = 19;
  public static final int OPERATINGUNITID = 20;
  public static final int CATEGORIAGR = 21;
  public static final int HRLOCATIONCODE = 22;
  public static final int HRLOCATIONDESC = 23;
  public static final int ZONA = 24;
  public static final int COSTCENTER = 25;
  public static final int RFC = 26;
  public static final int XXGAMINVASSIGNEXCEPT = 27;

  /**This is the default constructor (do not remove)
   */
  public XxGamPersonVtaUniformInfoVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute UserID
   */
  public String getUserID()
  {
    return (String) getAttributeInternal(USERID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute UserID
   */
  public void setUserID(String value)
  {
    setAttributeInternal(USERID, value);
  }

  /**Gets the attribute value for the calculated attribute PersonID
   */
  public String getPersonID()
  {
    return (String) getAttributeInternal(PERSONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonID
   */
  public void setPersonID(String value)
  {
    setAttributeInternal(PERSONID, value);
  }

  /**Gets the attribute value for the calculated attribute PersonFullName
   */
  public String getPersonFullName()
  {
    return (String) getAttributeInternal(PERSONFULLNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonFullName
   */
  public void setPersonFullName(String value)
  {
    setAttributeInternal(PERSONFULLNAME, value);
  }

  /**Gets the attribute value for the calculated attribute EmployeeNumber
   */
  public String getEmployeeNumber()
  {
    return (String) getAttributeInternal(EMPLOYEENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
   */
  public void setEmployeeNumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute PersonType
   */
  public String getPersonType()
  {
    return (String) getAttributeInternal(PERSONTYPE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonType
   */
  public void setPersonType(String value)
  {
    setAttributeInternal(PERSONTYPE, value);
  }

  /**Gets the attribute value for the calculated attribute PersonTypeID
   */
  public String getPersonTypeID()
  {
    return (String) getAttributeInternal(PERSONTYPEID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonTypeID
   */
  public void setPersonTypeID(String value)
  {
    setAttributeInternal(PERSONTYPEID, value);
  }

  /**Gets the attribute value for the calculated attribute Sex
   */
  public String getSex()
  {
    return (String) getAttributeInternal(SEX);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Sex
   */
  public void setSex(String value)
  {
    setAttributeInternal(SEX, value);
  }

  /**Gets the attribute value for the calculated attribute AssigmentID
   */
  public String getAssigmentID()
  {
    return (String) getAttributeInternal(ASSIGMENTID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute AssigmentID
   */
  public void setAssigmentID(String value)
  {
    setAttributeInternal(ASSIGMENTID, value);
  }

  /**Gets the attribute value for the calculated attribute Organization
   */
  public String getOrganization()
  {
    return (String) getAttributeInternal(ORGANIZATION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Organization
   */
  public void setOrganization(String value)
  {
    setAttributeInternal(ORGANIZATION, value);
  }

  /**Gets the attribute value for the calculated attribute OrganizationID
   */
  public String getOrganizationID()
  {
    return (String) getAttributeInternal(ORGANIZATIONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationID
   */
  public void setOrganizationID(String value)
  {
    setAttributeInternal(ORGANIZATIONID, value);
  }

  /**Gets the attribute value for the calculated attribute Grade
   */
  public String getGrade()
  {
    return (String) getAttributeInternal(GRADE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Grade
   */
  public void setGrade(String value)
  {
    setAttributeInternal(GRADE, value);
  }

  /**Gets the attribute value for the calculated attribute GradeID
   */
  public String getGradeID()
  {
    return (String) getAttributeInternal(GRADEID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute GradeID
   */
  public void setGradeID(String value)
  {
    setAttributeInternal(GRADEID, value);
  }

  /**Gets the attribute value for the calculated attribute Position
   */
  public String getPosition()
  {
    return (String) getAttributeInternal(POSITION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Position
   */
  public void setPosition(String value)
  {
    setAttributeInternal(POSITION, value);
  }

  /**Gets the attribute value for the calculated attribute PositionID
   */
  public String getPositionID()
  {
    return (String) getAttributeInternal(POSITIONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PositionID
   */
  public void setPositionID(String value)
  {
    setAttributeInternal(POSITIONID, value);
  }

  /**Gets the attribute value for the calculated attribute Payroll
   */
  public String getPayroll()
  {
    return (String) getAttributeInternal(PAYROLL);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Payroll
   */
  public void setPayroll(String value)
  {
    setAttributeInternal(PAYROLL, value);
  }

  /**Gets the attribute value for the calculated attribute PayrollID
   */
  public String getPayrollID()
  {
    return (String) getAttributeInternal(PAYROLLID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PayrollID
   */
  public void setPayrollID(String value)
  {
    setAttributeInternal(PAYROLLID, value);
  }

  /**Gets the attribute value for the calculated attribute Station
   */
  public String getStation()
  {
    return (String) getAttributeInternal(STATION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Station
   */
  public void setStation(String value)
  {
    setAttributeInternal(STATION, value);
  }

  /**Gets the attribute value for the calculated attribute AccountCombination
   */
  public String getAccountCombination()
  {
    return (String) getAttributeInternal(ACCOUNTCOMBINATION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute AccountCombination
   */
  public void setAccountCombination(String value)
  {
    setAttributeInternal(ACCOUNTCOMBINATION, value);
  }

  /**Gets the attribute value for the calculated attribute CodeCombinationID
   */
  public String getCodeCombinationID()
  {
    return (String) getAttributeInternal(CODECOMBINATIONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CodeCombinationID
   */
  public void setCodeCombinationID(String value)
  {
    setAttributeInternal(CODECOMBINATIONID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case USERID:
      return getUserID();
    case PERSONID:
      return getPersonID();
    case PERSONFULLNAME:
      return getPersonFullName();
    case EMPLOYEENUMBER:
      return getEmployeeNumber();
    case PERSONTYPE:
      return getPersonType();
    case PERSONTYPEID:
      return getPersonTypeID();
    case SEX:
      return getSex();
    case ASSIGMENTID:
      return getAssigmentID();
    case ORGANIZATION:
      return getOrganization();
    case ORGANIZATIONID:
      return getOrganizationID();
    case GRADE:
      return getGrade();
    case GRADEID:
      return getGradeID();
    case POSITION:
      return getPosition();
    case POSITIONID:
      return getPositionID();
    case PAYROLL:
      return getPayroll();
    case PAYROLLID:
      return getPayrollID();
    case STATION:
      return getStation();
    case ACCOUNTCOMBINATION:
      return getAccountCombination();
    case CODECOMBINATIONID:
      return getCodeCombinationID();
    case OPERATINGUNIT:
      return getOperatingUnit();
    case OPERATINGUNITID:
      return getOperatingUnitID();
    case CATEGORIAGR:
      return getCategoriaGr();
    case HRLOCATIONCODE:
      return getHrLocationCode();
    case HRLOCATIONDESC:
      return getHrLocationDesc();
    case ZONA:
      return getZona();
    case COSTCENTER:
      return getCostCenter();
    case RFC:
      return getRfc();
    case XXGAMINVASSIGNEXCEPT:
      return getXxGamInvAssignExcept();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case USERID:
      setUserID((String)value);
      return;
    case PERSONID:
      setPersonID((String)value);
      return;
    case PERSONFULLNAME:
      setPersonFullName((String)value);
      return;
    case EMPLOYEENUMBER:
      setEmployeeNumber((String)value);
      return;
    case PERSONTYPE:
      setPersonType((String)value);
      return;
    case PERSONTYPEID:
      setPersonTypeID((String)value);
      return;
    case SEX:
      setSex((String)value);
      return;
    case ASSIGMENTID:
      setAssigmentID((String)value);
      return;
    case ORGANIZATION:
      setOrganization((String)value);
      return;
    case ORGANIZATIONID:
      setOrganizationID((String)value);
      return;
    case GRADE:
      setGrade((String)value);
      return;
    case GRADEID:
      setGradeID((String)value);
      return;
    case POSITION:
      setPosition((String)value);
      return;
    case POSITIONID:
      setPositionID((String)value);
      return;
    case PAYROLL:
      setPayroll((String)value);
      return;
    case PAYROLLID:
      setPayrollID((String)value);
      return;
    case STATION:
      setStation((String)value);
      return;
    case ACCOUNTCOMBINATION:
      setAccountCombination((String)value);
      return;
    case CODECOMBINATIONID:
      setCodeCombinationID((String)value);
      return;
    case OPERATINGUNIT:
      setOperatingUnit((String)value);
      return;
    case OPERATINGUNITID:
      setOperatingUnitID((String)value);
      return;
    case CATEGORIAGR:
      setCategoriaGr((String)value);
      return;
    case HRLOCATIONCODE:
      setHrLocationCode((String)value);
      return;
    case HRLOCATIONDESC:
      setHrLocationDesc((String)value);
      return;
    case ZONA:
      setZona((String)value);
      return;
    case COSTCENTER:
      setCostCenter((String)value);
      return;
    case RFC:
      setRfc((String)value);
      return;
    case XXGAMINVASSIGNEXCEPT:
      setXxGamInvAssignExcept((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for the calculated attribute OperatingUnit
   */
  public String getOperatingUnit()
  {
    return (String) getAttributeInternal(OPERATINGUNIT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit
   */
  public void setOperatingUnit(String value)
  {
    setAttributeInternal(OPERATINGUNIT, value);
  }

  /**Gets the attribute value for the calculated attribute OperatingUnitID
   */
  public String getOperatingUnitID()
  {
    return (String) getAttributeInternal(OPERATINGUNITID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnitID
   */
  public void setOperatingUnitID(String value)
  {
    setAttributeInternal(OPERATINGUNITID, value);
  }

  /**Gets the attribute value for the calculated attribute CategoriaGr
   */
  public String getCategoriaGr()
  {
    return (String) getAttributeInternal(CATEGORIAGR);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CategoriaGr
   */
  public void setCategoriaGr(String value)
  {
    setAttributeInternal(CATEGORIAGR, value);
  }

  /**Gets the attribute value for the calculated attribute HrLocationCode
   */
  public String getHrLocationCode()
  {
    return (String) getAttributeInternal(HRLOCATIONCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute HrLocationCode
   */
  public void setHrLocationCode(String value)
  {
    setAttributeInternal(HRLOCATIONCODE, value);
  }

  /**Gets the attribute value for the calculated attribute HrLocationDesc
   */
  public String getHrLocationDesc()
  {
    return (String) getAttributeInternal(HRLOCATIONDESC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute HrLocationDesc
   */
  public void setHrLocationDesc(String value)
  {
    setAttributeInternal(HRLOCATIONDESC, value);
  }

  /**Gets the attribute value for the calculated attribute Zona
   */
  public String getZona()
  {
    return (String) getAttributeInternal(ZONA);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Zona
   */
  public void setZona(String value)
  {
    setAttributeInternal(ZONA, value);
  }

  /**Gets the attribute value for the calculated attribute CostCenter
   */
  public String getCostCenter()
  {
    return (String) getAttributeInternal(COSTCENTER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CostCenter
   */
  public void setCostCenter(String value)
  {
    setAttributeInternal(COSTCENTER, value);
  }

  /**Gets the attribute value for the calculated attribute Rfc
   */
  public String getRfc()
  {
    return (String) getAttributeInternal(RFC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Rfc
   */
  public void setRfc(String value)
  {
    setAttributeInternal(RFC, value);
  }

  /**Gets the attribute value for the calculated attribute XxGamInvAssignExcept
   */
  public String getXxGamInvAssignExcept()
  {
    return (String) getAttributeInternal(XXGAMINVASSIGNEXCEPT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute XxGamInvAssignExcept
   */
  public void setXxGamInvAssignExcept(String value)
  {
    setAttributeInternal(XXGAMINVASSIGNEXCEPT, value);
  }
}
