package xxgam.oracle.apps.xbol.maf.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaGeneralAndTicketPVORowImpl extends OAViewRowImpl
{
  public static final int REQUESTERNAME = 0;
  public static final int FOLIO = 1;
  public static final int STATUSFRANCHISE = 2;
  public static final int STATUSDESC = 3;
  public static final int REQUESTPAYMENTDATE = 4;
  public static final int ID = 5;
  public static final int TYPEEMISSION = 6;
  public static final int TYPEEMISSIONDSC = 7;
  public static final int APPROVERID = 8;
  public static final int BENEFICIARY = 9;
  public static final int RELATIONSHIP = 10;
  public static final int BENEFITS = 11;
  public static final int COMPANY = 12;
  public static final int GENERALREQID = 13;
  public static final int PAYMENTREQID = 14;
  public static final int TIPOSOLICITUD = 15;
  public static final int STATUSNOTIFICATION = 16;
  public static final int STATUSNOTIFICATIONDESC = 17;
  public static final int TICKETOFFICE = 18;
  public static final int TICKETOFFICECODE = 19;
  public static final int NUMBERPAYMENT = 20;
  public static final int OPERATINGUNIT = 21;
  public static final int ORIGIN = 22;

  /**This is the default constructor (do not remove)
   */
    public XxGamMaGeneralAndTicketPVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute RequesterName
     */
    public String getRequesterName() {
        return (String) getAttributeInternal(REQUESTERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequesterName
     */
    public void setRequesterName(String value) {
        setAttributeInternal(REQUESTERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute Folio
     */
    public String getFolio() {
        return (String) getAttributeInternal(FOLIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Folio
     */
    public void setFolio(String value) {
        setAttributeInternal(FOLIO, value);
    }

    /**Gets the attribute value for the calculated attribute StatusFranchise
     */
    public String getStatusFranchise() {
        return (String) getAttributeInternal(STATUSFRANCHISE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusFranchise
     */
    public void setStatusFranchise(String value) {
        setAttributeInternal(STATUSFRANCHISE, value);
    }

    /**Gets the attribute value for the calculated attribute StatusDesc
     */
    public String getStatusDesc() {
        return (String) getAttributeInternal(STATUSDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusDesc
     */
    public void setStatusDesc(String value) {
        setAttributeInternal(STATUSDESC, value);
    }

    /**Gets the attribute value for the calculated attribute RequestPaymentDate
     */
    public Date getRequestPaymentDate() {
        return (Date) getAttributeInternal(REQUESTPAYMENTDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequestPaymentDate
     */
    public void setRequestPaymentDate(Date value) {
        setAttributeInternal(REQUESTPAYMENTDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute TypeEmission
     */
    public String getTypeEmission() {
        return (String) getAttributeInternal(TYPEEMISSION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeEmission
     */
    public void setTypeEmission(String value) {
        setAttributeInternal(TYPEEMISSION, value);
    }

    /**Gets the attribute value for the calculated attribute TypeEmissionDsc
     */
    public String getTypeEmissionDsc() {
        return (String) getAttributeInternal(TYPEEMISSIONDSC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeEmissionDsc
     */
    public void setTypeEmissionDsc(String value) {
        setAttributeInternal(TYPEEMISSIONDSC, value);
    }

    /**Gets the attribute value for the calculated attribute ApproverId
     */
    public Number getApproverId() {
        return (Number) getAttributeInternal(APPROVERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverId
     */
    public void setApproverId(Number value) {
        setAttributeInternal(APPROVERID, value);
    }

    /**Gets the attribute value for the calculated attribute Beneficiary
     */
    public String getBeneficiary() {
        return (String) getAttributeInternal(BENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Beneficiary
     */
    public void setBeneficiary(String value) {
        setAttributeInternal(BENEFICIARY, value);
    }

    /**Gets the attribute value for the calculated attribute Relationship
     */
    public String getRelationship() {
        return (String) getAttributeInternal(RELATIONSHIP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Relationship
     */
    public void setRelationship(String value) {
        setAttributeInternal(RELATIONSHIP, value);
    }

    /**Gets the attribute value for the calculated attribute Benefits
     */
    public String getBenefits() {
        return (String) getAttributeInternal(BENEFITS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Benefits
     */
    public void setBenefits(String value) {
        setAttributeInternal(BENEFITS, value);
    }

    /**Gets the attribute value for the calculated attribute Company
     */
    public String getCompany() {
        return (String) getAttributeInternal(COMPANY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Company
     */
    public void setCompany(String value) {
        setAttributeInternal(COMPANY, value);
    }

    /**Gets the attribute value for the calculated attribute GeneralReqId
     */
    public Number getGeneralReqId() {
        return (Number) getAttributeInternal(GENERALREQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute GeneralReqId
     */
    public void setGeneralReqId(Number value) {
        setAttributeInternal(GENERALREQID, value);
    }

    /**Gets the attribute value for the calculated attribute PaymentReqId
     */
    public Number getPaymentReqId() {
        return (Number) getAttributeInternal(PAYMENTREQID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PaymentReqId
     */
    public void setPaymentReqId(Number value) {
        setAttributeInternal(PAYMENTREQID, value);
    }

    /**Gets the attribute value for the calculated attribute TipoSolicitud
     */
    public String getTipoSolicitud() {
        return (String) getAttributeInternal(TIPOSOLICITUD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipoSolicitud
     */
    public void setTipoSolicitud(String value) {
        setAttributeInternal(TIPOSOLICITUD, value);
    }

    /**Gets the attribute value for the calculated attribute StatusNotification
     */
    public String getStatusNotification() {
        return (String) getAttributeInternal(STATUSNOTIFICATION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusNotification
     */
    public void setStatusNotification(String value) {
        setAttributeInternal(STATUSNOTIFICATION, value);
    }

    /**Gets the attribute value for the calculated attribute StatusNotificationDesc
     */
    public String getStatusNotificationDesc() {
        return (String) getAttributeInternal(STATUSNOTIFICATIONDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusNotificationDesc
     */
    public void setStatusNotificationDesc(String value) {
        setAttributeInternal(STATUSNOTIFICATIONDESC, value);
    }

    /**Gets the attribute value for the calculated attribute TicketOffice
     */
    public String getTicketOffice() {
        return (String) getAttributeInternal(TICKETOFFICE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TicketOffice
     */
    public void setTicketOffice(String value) {
        setAttributeInternal(TICKETOFFICE, value);
    }

    /**Gets the attribute value for the calculated attribute TicketOfficeCode
     */
    public String getTicketOfficeCode() {
        return (String) getAttributeInternal(TICKETOFFICECODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TicketOfficeCode
     */
    public void setTicketOfficeCode(String value) {
        setAttributeInternal(TICKETOFFICECODE, value);
    }

    /**Gets the attribute value for the calculated attribute NumberPayment
     */
    public String getNumberPayment() {
        return (String) getAttributeInternal(NUMBERPAYMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumberPayment
     */
    public void setNumberPayment(String value) {
        setAttributeInternal(NUMBERPAYMENT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
    switch (index)
    {
    case REQUESTERNAME:
      return getRequesterName();
    case FOLIO:
      return getFolio();
    case STATUSFRANCHISE:
      return getStatusFranchise();
    case STATUSDESC:
      return getStatusDesc();
    case REQUESTPAYMENTDATE:
      return getRequestPaymentDate();
    case ID:
      return getId();
    case TYPEEMISSION:
      return getTypeEmission();
    case TYPEEMISSIONDSC:
      return getTypeEmissionDsc();
    case APPROVERID:
      return getApproverId();
    case BENEFICIARY:
      return getBeneficiary();
    case RELATIONSHIP:
      return getRelationship();
    case BENEFITS:
      return getBenefits();
    case COMPANY:
      return getCompany();
    case GENERALREQID:
      return getGeneralReqId();
    case PAYMENTREQID:
      return getPaymentReqId();
    case TIPOSOLICITUD:
      return getTipoSolicitud();
    case STATUSNOTIFICATION:
      return getStatusNotification();
    case STATUSNOTIFICATIONDESC:
      return getStatusNotificationDesc();
    case TICKETOFFICE:
      return getTicketOffice();
    case TICKETOFFICECODE:
      return getTicketOfficeCode();
    case NUMBERPAYMENT:
      return getNumberPayment();
    case OPERATINGUNIT:
      return getOperatingUnit();
    case ORIGIN:
      return getOrigin();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
    switch (index)
    {
    case STATUSFRANCHISE:
      setStatusFranchise((String)value);
      return;
    case ID:
      setId((Number)value);
      return;
    case TYPEEMISSIONDSC:
      setTypeEmissionDsc((String)value);
      return;
    case APPROVERID:
      setApproverId((Number)value);
      return;
    case BENEFICIARY:
      setBeneficiary((String)value);
      return;
    case RELATIONSHIP:
      setRelationship((String)value);
      return;
    case BENEFITS:
      setBenefits((String)value);
      return;
    case COMPANY:
      setCompany((String)value);
      return;
    case GENERALREQID:
      setGeneralReqId((Number)value);
      return;
    case PAYMENTREQID:
      setPaymentReqId((Number)value);
      return;
    case TIPOSOLICITUD:
      setTipoSolicitud((String)value);
      return;
    case STATUSNOTIFICATION:
      setStatusNotification((String)value);
      return;
    case STATUSNOTIFICATIONDESC:
      setStatusNotificationDesc((String)value);
      return;
    case TICKETOFFICE:
      setTicketOffice((String)value);
      return;
    case TICKETOFFICECODE:
      setTicketOfficeCode((String)value);
      return;
    case NUMBERPAYMENT:
      setNumberPayment((String)value);
      return;
    case OPERATINGUNIT:
      setOperatingUnit((String)value);
      return;
    case ORIGIN:
      setOrigin((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for the calculated attribute OperatingUnit
   */
  public String getOperatingUnit()
  {
    return (String) getAttributeInternal(OPERATINGUNIT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit
   */
  public void setOperatingUnit(String value)
  {
    setAttributeInternal(OPERATINGUNIT, value);
  }

  /**Gets the attribute value for the calculated attribute Origin
   */
  public String getOrigin()
  {
    return (String) getAttributeInternal(ORIGIN);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Origin
   */
  public void setOrigin(String value)
  {
    setAttributeInternal(ORIGIN, value);
  }
}
