package xxgam.oracle.apps.xbol.maf.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;

import xxgam.oracle.apps.xbol.maf.utils.XxGamConstantsUtil;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaPasajerosInfoEOImpl extends OAEntityImpl
{
  public static final int ID = 0;
  public static final int TICKETPID = 1;
  public static final int NAME = 2;
  public static final int FHONENUMBER = 3;
  public static final int TICKETNUMBER = 4;
  public static final int CREATIONDATE = 5;
  public static final int CREATEDBY = 6;
  public static final int LASTUPDATEDATE = 7;
  public static final int LASTUPDATEDBY = 8;
  public static final int LASTUPDATELOGIN = 9;
  public static final int XXGAMMATICKETPEO = 10;


  private static OAEntityDefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public XxGamMaPasajerosInfoEOImpl()
  {
  }


  /**Retrieves the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    if (mDefinitionObject == null)
    {
      mDefinitionObject = 
          (OAEntityDefImpl)EntityDefImpl.findDefObject("xxgam.oracle.apps.xbol.maf.server.XxGamMaPasajerosInfoEO");
    }
    return mDefinitionObject;
  }

  /**Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**Gets the attribute value for TicketPId, using the alias name TicketPId
   */
  public Number getTicketPId()
  {
    return (Number)getAttributeInternal(TICKETPID);
  }

  /**Sets <code>value</code> as the attribute value for TicketPId
   */
  public void setTicketPId(Number value)
  {
    setAttributeInternal(TICKETPID, value);
  }

  /**Gets the attribute value for Name, using the alias name Name
   */
  public String getName()
  {
    return (String)getAttributeInternal(NAME);
  }

  /**Sets <code>value</code> as the attribute value for Name
   */
  public void setName(String value)
  {
    setAttributeInternal(NAME, value);
  }

  /**Gets the attribute value for FhoneNumber, using the alias name FhoneNumber
   */
  public String getFhoneNumber()
  {
    return (String)getAttributeInternal(FHONENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for FhoneNumber
   */
  public void setFhoneNumber(String value)
  {
    setAttributeInternal(FHONENUMBER, value);
  }

  /**Gets the attribute value for TicketNumber, using the alias name TicketNumber
   */
  public String getTicketNumber()
  {
    return (String)getAttributeInternal(TICKETNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for TicketNumber
   */
  public void setTicketNumber(String value)
  {
    setAttributeInternal(TICKETNUMBER, value);
  }

  /**Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case ID:
      return getId();
    case TICKETPID:
      return getTicketPId();
    case NAME:
      return getName();
    case FHONENUMBER:
      return getFhoneNumber();
    case TICKETNUMBER:
      return getTicketNumber();
    case CREATIONDATE:
      return getCreationDate();
    case CREATEDBY:
      return getCreatedBy();
    case LASTUPDATEDATE:
      return getLastUpdateDate();
    case LASTUPDATEDBY:
      return getLastUpdatedBy();
    case LASTUPDATELOGIN:
      return getLastUpdateLogin();
    case XXGAMMATICKETPEO:
      return getXxGamMaTicketPEO();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case ID:
      setId((Number)value);
      return;
    case TICKETPID:
      setTicketPId((Number)value);
      return;
    case NAME:
      setName((String)value);
      return;
    case FHONENUMBER:
      setFhoneNumber((String)value);
      return;
    case TICKETNUMBER:
      setTicketNumber((String)value);
      return;
    case CREATIONDATE:
      setCreationDate((Date)value);
      return;
    case CREATEDBY:
      setCreatedBy((Number)value);
      return;
    case LASTUPDATEDATE:
      setLastUpdateDate((Date)value);
      return;
    case LASTUPDATEDBY:
      setLastUpdatedBy((Number)value);
      return;
    case LASTUPDATELOGIN:
      setLastUpdateLogin((Number)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the associated entity XxGamMaTicketPEOImpl
   */
  public XxGamMaTicketPEOImpl getXxGamMaTicketPEO()
  {
    return (XxGamMaTicketPEOImpl)getAttributeInternal(XXGAMMATICKETPEO);
  }

  /**Sets <code>value</code> as the associated entity XxGamMaTicketPEOImpl
   */
  public void setXxGamMaTicketPEO(XxGamMaTicketPEOImpl value)
  {
    setAttributeInternal(XXGAMMATICKETPEO, value);
  }


  /**Add attribute defaulting logic in this method.
   */
  public void create(AttributeList attributeList) {


      //Obtiene la clave primaria
      Number pasajerosInfoId = null;
      pasajerosInfoId = getOADBTransaction().getSequenceValue("XXGAM_MA_PASAJEROS_INFO_S");

      //Inicializa la clave primaria
      if (pasajerosInfoId != null)
          setId(pasajerosInfoId);
      System.out.println("Se creo PasajeroInfoID  " + pasajerosInfoId);
      super.create(attributeList);
  }


  /**Creates a Key object based on given key constituents
   */
  public static Key createPrimaryKey(Number id)
  {
    return new Key(new Object[]{id});
  }
}
