package xxgam.oracle.apps.xbol.maf.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxgamMaTicketP2EOImpl extends OAEntityImpl {
    public static final int ID = 0;
    public static final int PAYMENTREQID = 1;
    public static final int PNR = 2;
    public static final int TICKETOFFICE = 3;
    public static final int CONTACTPHONE = 4;
    public static final int EMAIL = 5;
    public static final int TYPEEMISSION = 6;
    public static final int FOLIO = 7;
    public static final int CREATIONDATE = 8;
    public static final int CREATEDBY = 9;
    public static final int LASTUPDATEDATE = 10;
    public static final int LASTUPDATELOGIN = 11;
    public static final int ROWID = 12;
    public static final int GENERALREQID = 13;
    public static final int BENEFICIARY = 14;
    public static final int RELATIONSHIP = 15;
    public static final int BENEFITS = 16;
    public static final int COMPANY = 17;
    public static final int LASTUPDATEDBY = 18;
    public static final int XXGAMMAPAYMENTREQEO = 20;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxgamMaTicketP2EOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxgam.oracle.apps.xbol.maf.server.XxgamMaTicketP2EO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for PaymentReqId, using the alias name PaymentReqId
     */
    public Number getPaymentReqId() {
        return (Number)getAttributeInternal(PAYMENTREQID);
    }

    /**Sets <code>value</code> as the attribute value for PaymentReqId
     */
    public void setPaymentReqId(Number value) {
        setAttributeInternal(PAYMENTREQID, value);
    }

    /**Gets the attribute value for Pnr, using the alias name Pnr
     */
    public String getPnr() {
        return (String)getAttributeInternal(PNR);
    }

    /**Sets <code>value</code> as the attribute value for Pnr
     */
    public void setPnr(String value) {
        setAttributeInternal(PNR, value);
    }

    /**Gets the attribute value for TicketOffice, using the alias name TicketOffice
     */
    public String getTicketOffice() {
        return (String)getAttributeInternal(TICKETOFFICE);
    }

    /**Sets <code>value</code> as the attribute value for TicketOffice
     */
    public void setTicketOffice(String value) {
        setAttributeInternal(TICKETOFFICE, value);
    }

    /**Gets the attribute value for ContactPhone, using the alias name ContactPhone
     */
    public String getContactPhone() {
        return (String)getAttributeInternal(CONTACTPHONE);
    }

    /**Sets <code>value</code> as the attribute value for ContactPhone
     */
    public void setContactPhone(String value) {
        setAttributeInternal(CONTACTPHONE, value);
    }

    /**Gets the attribute value for Email, using the alias name Email
     */
    public String getEmail() {
        return (String)getAttributeInternal(EMAIL);
    }

    /**Sets <code>value</code> as the attribute value for Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**Gets the attribute value for TypeEmission, using the alias name TypeEmission
     */
    public String getTypeEmission() {
        return (String)getAttributeInternal(TYPEEMISSION);
    }

    /**Sets <code>value</code> as the attribute value for TypeEmission
     */
    public void setTypeEmission(String value) {
        setAttributeInternal(TYPEEMISSION, value);
    }

    /**Gets the attribute value for Folio, using the alias name Folio
     */
    public String getFolio() {
        return (String)getAttributeInternal(FOLIO);
    }

    /**Sets <code>value</code> as the attribute value for Folio
     */
    public void setFolio(String value) {
        setAttributeInternal(FOLIO, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for RowID, using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID)getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case PAYMENTREQID:
            return getPaymentReqId();
        case PNR:
            return getPnr();
        case TICKETOFFICE:
            return getTicketOffice();
        case CONTACTPHONE:
            return getContactPhone();
        case EMAIL:
            return getEmail();
        case TYPEEMISSION:
            return getTypeEmission();
        case FOLIO:
            return getFolio();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ROWID:
            return getRowID();
        case GENERALREQID:
            return getGeneralReqId();
        case BENEFICIARY:
            return getBeneficiary();
        case RELATIONSHIP:
            return getRelationship();
        case BENEFITS:
            return getBenefits();
        case COMPANY:
            return getCompany();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case PAYMENTREQID:
            setPaymentReqId((Number)value);
            return;
        case PNR:
            setPnr((String)value);
            return;
        case TICKETOFFICE:
            setTicketOffice((String)value);
            return;
        case CONTACTPHONE:
            setContactPhone((String)value);
            return;
        case EMAIL:
            setEmail((String)value);
            return;
        case TYPEEMISSION:
            setTypeEmission((String)value);
            return;
        case FOLIO:
            setFolio((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case GENERALREQID:
            setGeneralReqId((Number)value);
            return;
        case BENEFICIARY:
            setBeneficiary((String)value);
            return;
        case RELATIONSHIP:
            setRelationship((String)value);
            return;
        case BENEFITS:
            setBenefits((String)value);
            return;
        case COMPANY:
            setCompany((String)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity XxGamMaPaymentReqEOImpl
     */
    public XxGamMaPaymentReqEOImpl getXxGamMaPaymentReqEO() {
        return (XxGamMaPaymentReqEOImpl)getAttributeInternal(XXGAMMAPAYMENTREQEO);
    }

    /**Sets <code>value</code> as the associated entity XxGamMaPaymentReqEOImpl
     */
    public void setXxGamMaPaymentReqEO(XxGamMaPaymentReqEOImpl value) {
        setAttributeInternal(XXGAMMAPAYMENTREQEO, value);
    }

    public void setLastUpdatedBy(Number number) {
    }

    /**Gets the attribute value for GeneralReqId, using the alias name GeneralReqId
     */
    public Number getGeneralReqId() {
        return (Number)getAttributeInternal(GENERALREQID);
    }

    /**Sets <code>value</code> as the attribute value for GeneralReqId
     */
    public void setGeneralReqId(Number value) {
        setAttributeInternal(GENERALREQID, value);
    }

    /**Gets the attribute value for Beneficiary, using the alias name Beneficiary
     */
    public String getBeneficiary() {
        return (String)getAttributeInternal(BENEFICIARY);
    }

    /**Sets <code>value</code> as the attribute value for Beneficiary
     */
    public void setBeneficiary(String value) {
        setAttributeInternal(BENEFICIARY, value);
    }

    /**Gets the attribute value for Relationship, using the alias name Relationship
     */
    public String getRelationship() {
        return (String)getAttributeInternal(RELATIONSHIP);
    }

    /**Sets <code>value</code> as the attribute value for Relationship
     */
    public void setRelationship(String value) {
        setAttributeInternal(RELATIONSHIP, value);
    }

    /**Gets the attribute value for Benefits, using the alias name Benefits
     */
    public String getBenefits() {
        return (String)getAttributeInternal(BENEFITS);
    }

    /**Sets <code>value</code> as the attribute value for Benefits
     */
    public void setBenefits(String value) {
        setAttributeInternal(BENEFITS, value);
    }

    /**Gets the attribute value for Company, using the alias name Company
     */
    public String getCompany() {
        return (String)getAttributeInternal(COMPANY);
    }

    /**Sets <code>value</code> as the attribute value for Company
     */
    public void setCompany(String value) {
        setAttributeInternal(COMPANY, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }
}
