package xxgam.oracle.apps.xbol.maf.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxgamValidaTipoPersonaVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxgamValidaTipoPersonaVOImpl() {
    }

    public void obtieneTipoPersona(Number userId) {
       this.setWhereClause((String)null);
       this.setWhereClauseParams((Object[])null);
       String whereClause = " PERSON_ID = (SELECT EMPLOYEE_ID\n" + 
                                          "  FROM FND_USER \n" + 
                                          " WHERE 1 = 1 " + 
                                          "   AND USER_ID = " + userId + ")";
       this.setWhereClause(whereClause);
       this.executeQuery();
    }
}
