package xxgam.oracle.apps.xbol.maf.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaGeneralReqVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int NUMBERPAYMENT = 1;
    public static final int EMPLOYEEID = 2;
    public static final int REQUESTPAYMENTDATE = 3;
    public static final int STATUSREQUEST = 4;
    public static final int TOTALPAYMENT = 5;
    public static final int PURPOSE = 6;
    public static final int APPROVALDATE = 7;
    public static final int APPROVERID = 8;
    public static final int APPROVERALTID = 9;
    public static final int COSTCENTER = 10;
    public static final int COSTCENTERFLEX = 11;
    public static final int GROUPPAYMENT = 12;
    public static final int TEMPLATEPAYMENT = 13;
    public static final int CURRENCYCODE = 14;
    public static final int VIRTUALCARD = 15;
    public static final int STATUSNOTIFICATION = 16;
    public static final int CREATIONDATE = 17;
    public static final int CREATEDBY = 18;
    public static final int LASTUPDATELOGIN = 19;
    public static final int LASTUPDATEDBY = 20;
    public static final int LASTUPDATEDATE = 21;
    public static final int ISVIEW = 22;
    public static final int PURPOSEDESCRIPTION = 23;
    public static final int STATUSDESCRIPTION = 24;
    public static final int CURRENCYNAME = 25;
    public static final int EMPLOYENAME = 26;
    public static final int APPROVERNAME = 27;
    public static final int APPROVERNAMEALT = 28;
    public static final int STATUSTICKET = 29;
    public static final int REPORTTYPE = 30;
    public static final int STATUSFRANCHISE = 31;
    public static final int TIPOSOLICITUD = 32;
    public static final int STATUSFRANCHISEDSC = 33;
    public static final int ISDETAIL = 34;
    public static final int REASON = 35;
    public static final int COMMENTS = 36;
    public static final int OPERATINGUNIT = 37;
    public static final int ORIGIN = 38;
    public static final int VCMEANINGXX = 39;
    public static final int FULLNAMEEMPLOYEE = 40;
    public static final int FULLNAMEAPPROVER = 41;
    public static final int FULLNAMEAPPROVERALT = 42;
    public static final int CURRENCYDESC = 43;
    public static final int TYPETEMPLATEDESC = 44;
    public static final int PURPOSEDESC = 45;
    public static final int COSTCENTERDESC = 46;
    public static final int COSTCENTERTMP = 47;
    public static final int ISAPPROVERBYSYS = 48;
    public static final int ISNOTAPPROVERBYSYS = 49;
    public static final int ISDISABLETEMPLATEPAYMENT = 50;
    public static final int ISDISABLETEMPLATEPAYMENTFLEX = 51;
    public static final int ISRESPFRANCHISE = 52;
    public static final int ISVISIBLEAPPROVERALT = 53;
    public static final int DEPARTTIME = 54;
    public static final int ARRIVALTIME = 55;
    public static final int XXGAMMAPAYMENTREQVO = 56;
    public static final int XXGAMMATICKETPVO = 57;

    /**This is the default constructor (do not remove)
     */
    public XxGamMaGeneralReqVORowImpl() {
    }

    /**Gets XxGamMaGeneralReqEO entity object.
     */
    public XxGamMaGeneralReqEOImpl getXxGamMaGeneralReqEO() {
        return (XxGamMaGeneralReqEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }


    /**Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
     */
    public Number getEmployeeId() {
        return (Number)getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for REQUEST_PAYMENT_DATE using the alias name RequestPaymentDate
     */
    public Date getRequestPaymentDate() {
        return (Date)getAttributeInternal(REQUESTPAYMENTDATE);
    }

    /**Sets <code>value</code> as attribute value for REQUEST_PAYMENT_DATE using the alias name RequestPaymentDate
     */
    public void setRequestPaymentDate(Date value) {
        setAttributeInternal(REQUESTPAYMENTDATE, value);
    }

    /**Gets the attribute value for STATUS_REQUEST using the alias name StatusRequest
     */
    public String getStatusRequest() {
        return (String)getAttributeInternal(STATUSREQUEST);
    }

    /**Sets <code>value</code> as attribute value for STATUS_REQUEST using the alias name StatusRequest
     */
    public void setStatusRequest(String value) {
        setAttributeInternal(STATUSREQUEST, value);
    }

    /**Gets the attribute value for TOTAL_PAYMENT using the alias name TotalPayment
     */
    public Number getTotalPayment() {
        return (Number)getAttributeInternal(TOTALPAYMENT);
    }

    /**Sets <code>value</code> as attribute value for TOTAL_PAYMENT using the alias name TotalPayment
     */
    public void setTotalPayment(Number value) {
        setAttributeInternal(TOTALPAYMENT, value);
    }

    /**Gets the attribute value for PURPOSE using the alias name Purpose
     */
    public String getPurpose() {
        return (String)getAttributeInternal(PURPOSE);
    }

    /**Sets <code>value</code> as attribute value for PURPOSE using the alias name Purpose
     */
    public void setPurpose(String value) {
        setAttributeInternal(PURPOSE, value);
    }

    /**Gets the attribute value for APPROVAL_DATE using the alias name ApprovalDate
     */
    public Date getApprovalDate() {
        return (Date)getAttributeInternal(APPROVALDATE);
    }

    /**Sets <code>value</code> as attribute value for APPROVAL_DATE using the alias name ApprovalDate
     */
    public void setApprovalDate(Date value) {
        setAttributeInternal(APPROVALDATE, value);
    }

    /**Gets the attribute value for APPROVER_ID using the alias name ApproverId
     */
    public Number getApproverId() {
        return (Number)getAttributeInternal(APPROVERID);
    }

    /**Sets <code>value</code> as attribute value for APPROVER_ID using the alias name ApproverId
     */
    public void setApproverId(Number value) {
        setAttributeInternal(APPROVERID, value);
    }

    /**Gets the attribute value for COST_CENTER using the alias name CostCenter
     */
    public Number getCostCenter() {
        return (Number)getAttributeInternal(COSTCENTER);
    }

    /**Sets <code>value</code> as attribute value for COST_CENTER using the alias name CostCenter
     */
    public void setCostCenter(Number value) {
        setAttributeInternal(COSTCENTER, value);
    }

    /**Gets the attribute value for GROUP_PAYMENT using the alias name GroupPayment
     */
    public String getGroupPayment() {
        return (String)getAttributeInternal(GROUPPAYMENT);
    }

    /**Sets <code>value</code> as attribute value for GROUP_PAYMENT using the alias name GroupPayment
     */
    public void setGroupPayment(String value) {
        setAttributeInternal(GROUPPAYMENT, value);
    }

    /**Gets the attribute value for TEMPLATE_PAYMENT using the alias name TemplatePayment
     */
    public Number getTemplatePayment() {
        return (Number)getAttributeInternal(TEMPLATEPAYMENT);
    }

    /**Sets <code>value</code> as attribute value for TEMPLATE_PAYMENT using the alias name TemplatePayment
     */
    public void setTemplatePayment(Number value) {
        setAttributeInternal(TEMPLATEPAYMENT, value);
    }

    /**Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode
     */
    public String getCurrencyCode() {
        return (String)getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for VIRTUAL_CARD using the alias name VirtualCard
     */
    public String getVirtualCard() {
        return (String)getAttributeInternal(VIRTUALCARD);
    }

    /**Sets <code>value</code> as attribute value for VIRTUAL_CARD using the alias name VirtualCard
     */
    public void setVirtualCard(String value) {

        if (value != null) {
            setAttributeInternal(VIRTUALCARD, value);
        }
    }

    /**Gets the attribute value for STATUS_NOTIFICATION using the alias name StatusNotification
     */
    public String getStatusNotification() {
        return (String)getAttributeInternal(STATUSNOTIFICATION);
    }

    /**Sets <code>value</code> as attribute value for STATUS_NOTIFICATION using the alias name StatusNotification
     */
    public void setStatusNotification(String value) {
        setAttributeInternal(STATUSNOTIFICATION, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link XxGamMaPaymentReqVO
     */
    public RowIterator getXxGamMaPaymentReqVO() {
        return (RowIterator)getAttributeInternal(XXGAMMAPAYMENTREQVO);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case NUMBERPAYMENT:
            return getNumberPayment();
        case EMPLOYEEID:
            return getEmployeeId();
        case REQUESTPAYMENTDATE:
            return getRequestPaymentDate();
        case STATUSREQUEST:
            return getStatusRequest();
        case TOTALPAYMENT:
            return getTotalPayment();
        case PURPOSE:
            return getPurpose();
        case APPROVALDATE:
            return getApprovalDate();
        case APPROVERID:
            return getApproverId();
        case APPROVERALTID:
            return getApproverAltId();
        case COSTCENTER:
            return getCostCenter();
        case COSTCENTERFLEX:
            return getCostCenterFlex();
        case GROUPPAYMENT:
            return getGroupPayment();
        case TEMPLATEPAYMENT:
            return getTemplatePayment();
        case CURRENCYCODE:
            return getCurrencyCode();
        case VIRTUALCARD:
            return getVirtualCard();
        case STATUSNOTIFICATION:
            return getStatusNotification();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case ISVIEW:
            return getIsView();
        case PURPOSEDESCRIPTION:
            return getPurposeDescription();
        case STATUSDESCRIPTION:
            return getStatusDescription();
        case CURRENCYNAME:
            return getCurrencyName();
        case EMPLOYENAME:
            return getEmployeName();
        case APPROVERNAME:
            return getApproverName();
        case APPROVERNAMEALT:
            return getApproverNameAlt();
        case STATUSTICKET:
            return getStatusTicket();
        case REPORTTYPE:
            return getReportType();
        case STATUSFRANCHISE:
            return getStatusFranchise();
        case TIPOSOLICITUD:
            return getTipoSolicitud();
        case STATUSFRANCHISEDSC:
            return getStatusFranchiseDsc();
        case ISDETAIL:
            return getIsDetail();
        case REASON:
            return getReason();
        case COMMENTS:
            return getComments();
        case OPERATINGUNIT:
            return getOperatingUnit();
        case ORIGIN:
            return getOrigin();
        case VCMEANINGXX:
            return getVcMeaningxx();
        case FULLNAMEEMPLOYEE:
            return getFullNameEmployee();
        case FULLNAMEAPPROVER:
            return getFullNameApprover();
        case FULLNAMEAPPROVERALT:
            return getFullNameApproverAlt();
        case CURRENCYDESC:
            return getCurrencyDesc();
        case TYPETEMPLATEDESC:
            return getTypeTemplateDesc();
        case PURPOSEDESC:
            return getPurposeDesc();
        case COSTCENTERDESC:
            return getCostCenterDesc();
        case COSTCENTERTMP:
            return getCostCenterTmp();
        case ISAPPROVERBYSYS:
            return getIsApproverBySys();
        case ISNOTAPPROVERBYSYS:
            return getIsNotApproverBySys();
        case ISDISABLETEMPLATEPAYMENT:
            return getIsDisableTemplatePayment();
        case ISDISABLETEMPLATEPAYMENTFLEX:
            return getIsDisableTemplatePaymentFlex();
        case ISRESPFRANCHISE:
            return getIsRespFranchise();
        case ISVISIBLEAPPROVERALT:
            return getIsVisibleApproverAlt();
        case DEPARTTIME:
            return getDepartTime();
        case ARRIVALTIME:
            return getArrivalTime();
        case XXGAMMATICKETPVO:
            return getXxGamMaTicketPVO();
        case XXGAMMAPAYMENTREQVO:
            return getXxGamMaPaymentReqVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case NUMBERPAYMENT:
            setNumberPayment((String)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case REQUESTPAYMENTDATE:
            setRequestPaymentDate((Date)value);
            return;
        case STATUSREQUEST:
            setStatusRequest((String)value);
            return;
        case TOTALPAYMENT:
            setTotalPayment((Number)value);
            return;
        case PURPOSE:
            setPurpose((String)value);
            return;
        case APPROVALDATE:
            setApprovalDate((Date)value);
            return;
        case APPROVERID:
            setApproverId((Number)value);
            return;
        case APPROVERALTID:
            setApproverAltId((Number)value);
            return;
        case COSTCENTER:
            setCostCenter((Number)value);
            return;
        case COSTCENTERFLEX:
            setCostCenterFlex((String)value);
            return;
        case GROUPPAYMENT:
            setGroupPayment((String)value);
            return;
        case TEMPLATEPAYMENT:
            setTemplatePayment((Number)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case VIRTUALCARD:
            setVirtualCard((String)value);
            return;
        case STATUSNOTIFICATION:
            setStatusNotification((String)value);
            return;
        case ISVIEW:
            setIsView((String)value);
            return;
        case PURPOSEDESCRIPTION:
            setPurposeDescription((String)value);
            return;
        case STATUSDESCRIPTION:
            setStatusDescription((String)value);
            return;
        case CURRENCYNAME:
            setCurrencyName((String)value);
            return;
        case EMPLOYENAME:
            setEmployeName((String)value);
            return;
        case APPROVERNAME:
            setApproverName((String)value);
            return;
        case APPROVERNAMEALT:
            setApproverNameAlt((String)value);
            return;
        case STATUSTICKET:
            setStatusTicket((String)value);
            return;
        case REPORTTYPE:
            setReportType((String)value);
            return;
        case STATUSFRANCHISE:
            setStatusFranchise((String)value);
            return;
        case TIPOSOLICITUD:
            setTipoSolicitud((String)value);
            return;
        case STATUSFRANCHISEDSC:
            setStatusFranchiseDsc((String)value);
            return;
        case ISDETAIL:
            setIsDetail((String)value);
            return;
        case REASON:
            setReason((String)value);
            return;
        case COMMENTS:
            setComments((String)value);
            return;
        case OPERATINGUNIT:
            setOperatingUnit((String)value);
            return;
        case ORIGIN:
            setOrigin((String)value);
            return;
        case VCMEANINGXX:
            setVcMeaningxx((String)value);
            return;
        case FULLNAMEEMPLOYEE:
            setFullNameEmployee((String)value);
            return;
        case FULLNAMEAPPROVER:
            setFullNameApprover((String)value);
            return;
        case FULLNAMEAPPROVERALT:
            setFullNameApproverAlt((String)value);
            return;
        case CURRENCYDESC:
            setCurrencyDesc((String)value);
            return;
        case TYPETEMPLATEDESC:
            setTypeTemplateDesc((String)value);
            return;
        case PURPOSEDESC:
            setPurposeDesc((String)value);
            return;
        case COSTCENTERDESC:
            setCostCenterDesc((String)value);
            return;
        case COSTCENTERTMP:
            setCostCenterTmp((String)value);
            return;
        case ISAPPROVERBYSYS:
            setIsApproverBySys((Boolean)value);
            return;
        case ISNOTAPPROVERBYSYS:
            setIsNotApproverBySys((Boolean)value);
            return;
        case ISDISABLETEMPLATEPAYMENT:
            setIsDisableTemplatePayment((Boolean)value);
            return;
        case ISDISABLETEMPLATEPAYMENTFLEX:
            setIsDisableTemplatePaymentFlex((Boolean)value);
            return;
        case ISRESPFRANCHISE:
            setIsRespFranchise((Boolean)value);
            return;
        case ISVISIBLEAPPROVERALT:
            setIsVisibleApproverAlt((Boolean)value);
            return;
        case DEPARTTIME:
            setDepartTime((String)value);
            return;
        case ARRIVALTIME:
            setArrivalTime((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute IsView
     */
    public String getIsView() {
        return (String)getAttributeInternal(ISVIEW);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsView
     */
    public void setIsView(String value) {
        setAttributeInternal(ISVIEW, value);
    }

    /**Gets the attribute value for the calculated attribute PurposeDescription
     */
    public String getPurposeDescription() {
        return (String)getAttributeInternal(PURPOSEDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PurposeDescription
     */
    public void setPurposeDescription(String value) {
        setAttributeInternal(PURPOSEDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute StatusDescription
     */
    public String getStatusDescription() {
        return (String)getAttributeInternal(STATUSDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusDescription
     */
    public void setStatusDescription(String value) {
        setAttributeInternal(STATUSDESCRIPTION, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyName
     */
    public String getCurrencyName() {
        return (String)getAttributeInternal(CURRENCYNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyName
     */
    public void setCurrencyName(String value) {
        setAttributeInternal(CURRENCYNAME, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeName
     */
    public String getEmployeName() {
        return (String)getAttributeInternal(EMPLOYENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeName
     */
    public void setEmployeName(String value) {
        setAttributeInternal(EMPLOYENAME, value);
    }

    /**Gets the attribute value for the calculated attribute ApproverName
     */
    public String getApproverName() {
        return (String)getAttributeInternal(APPROVERNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverName
     */
    public void setApproverName(String value) {
        setAttributeInternal(APPROVERNAME, value);
    }

    /**Gets the attribute value for the calculated attribute StatusTicket
     */
    public String getStatusTicket() {
        return (String)getAttributeInternal(STATUSTICKET);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusTicket
     */
    public void setStatusTicket(String value) {
        setAttributeInternal(STATUSTICKET, value);
    }

    /**Gets the attribute value for the calculated attribute ReportType
     */
    public String getReportType() {
        return (String)getAttributeInternal(REPORTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ReportType
     */
    public void setReportType(String value) {
        setAttributeInternal(REPORTTYPE, value);
    }

    /**Gets the attribute value for the calculated attribute StatusFranchise
     */
    public String getStatusFranchise() {
        return (String)getAttributeInternal(STATUSFRANCHISE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusFranchise
     */
    public void setStatusFranchise(String value) {
        setAttributeInternal(STATUSFRANCHISE, value);
    }

    /**Gets the attribute value for the calculated attribute FullNameEmployee
     */
    public String getFullNameEmployee() {
        return (String)getAttributeInternal(FULLNAMEEMPLOYEE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullNameEmployee
     */
    public void setFullNameEmployee(String value) {
        populateAttribute(FULLNAMEEMPLOYEE, value);
    }

    /**Gets the attribute value for the calculated attribute FullNameApprover
     */
    public String getFullNameApprover() {
        return (String)getAttributeInternal(FULLNAMEAPPROVER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullNameApprover
     */
    public void setFullNameApprover(String value) {
        populateAttribute(FULLNAMEAPPROVER, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyDesc
     */
    public String getCurrencyDesc() {
        return (String)getAttributeInternal(CURRENCYDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyDesc
     */
    public void setCurrencyDesc(String value) {
        populateAttribute(CURRENCYDESC, value);
    }

    /**Gets the attribute value for the calculated attribute TypeTemplateDesc
     */
    public String getTypeTemplateDesc() {
        return (String)getAttributeInternal(TYPETEMPLATEDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeTemplateDesc
     */
    public void setTypeTemplateDesc(String value) {
        populateAttribute(TYPETEMPLATEDESC, value);
    }

    /**Gets the attribute value for the calculated attribute PurposeDesc
     */
    public String getPurposeDesc() {
        return (String)getAttributeInternal(PURPOSEDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PurposeDesc
     */
    public void setPurposeDesc(String value) {
        populateAttribute(PURPOSEDESC, value);
    }

    /**Gets the attribute value for the calculated attribute CostCenterDesc
     */
    public String getCostCenterDesc() {
        return (String)getAttributeInternal(COSTCENTERDESC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CostCenterDesc
     */
    public void setCostCenterDesc(String value) {
        populateAttribute(COSTCENTERDESC, value);
    }


    /**Gets the associated <code>RowIterator</code> using master-detail link XxGamMaTicketPVO
     */
    public RowIterator getXxGamMaTicketPVO() {
        return (RowIterator)getAttributeInternal(XXGAMMATICKETPVO);
    }

    /**Gets the attribute value for the calculated attribute TipoSolicitud
     */
    public String getTipoSolicitud() {
        return (String)getAttributeInternal(TIPOSOLICITUD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TipoSolicitud
     */
    public void setTipoSolicitud(String value) {
        setAttributeInternal(TIPOSOLICITUD, value);
    }

    /**Gets the attribute value for the calculated attribute CostCenterTmp
     */
    public String getCostCenterTmp() {
        return (String)getAttributeInternal(COSTCENTERTMP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CostCenterTmp
     */
    public void setCostCenterTmp(String value) {
        setAttributeInternal(COSTCENTERTMP, value);
    }

    /**Gets the attribute value for the calculated attribute StatusFranchiseDsc
     */
    public String getStatusFranchiseDsc() {
        return (String)getAttributeInternal(STATUSFRANCHISEDSC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusFranchiseDsc
     */
    public void setStatusFranchiseDsc(String value) {
        setAttributeInternal(STATUSFRANCHISEDSC, value);
    }

    /**Gets the attribute value for the calculated attribute IsDetail
     */
    public String getIsDetail() {
        return (String)getAttributeInternal(ISDETAIL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsDetail
     */
    public void setIsDetail(String value) {
        populateAttribute(ISDETAIL, value);
    }

    /**Gets the attribute value for the calculated attribute IsApproverBySys
     */
    public Boolean getIsApproverBySys() {
        return (Boolean)getAttributeInternal(ISAPPROVERBYSYS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsApproverBySys
     */
    public void setIsApproverBySys(Boolean value) {
        populateAttribute(ISAPPROVERBYSYS, value);
    }


    /**Gets the attribute value for the calculated attribute IsNotApproverBySys
     */
    public Boolean getIsNotApproverBySys() {

        if (getIsApproverBySys() != null) {
            if (getIsApproverBySys().booleanValue()) {
                setIsNotApproverBySys(false);
            } else {
                setIsNotApproverBySys(true);
            }
        }

        return (Boolean)getAttributeInternal(ISNOTAPPROVERBYSYS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsNotApproverBySys
     */
    public void setIsNotApproverBySys(Boolean value) {
        populateAttribute(ISNOTAPPROVERBYSYS, value);
    }

    /**Gets the attribute value for the calculated attribute NumberPayment
     */
    public String getNumberPayment() {
        return (String)getAttributeInternal(NUMBERPAYMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumberPayment
     */
    public void setNumberPayment(String value) {
        setAttributeInternal(NUMBERPAYMENT, value);
    }

    /**Gets the attribute value for the calculated attribute IsDisableTemplatePayment
     */
    public Boolean getIsDisableTemplatePayment() {

        if (getIsRespFranchise() != null) {
            if (getIsRespFranchise().booleanValue()) {
                setIsDisableTemplatePayment(true);
            } else {
                if (getCostCenterFlex() != null) {
                    setIsDisableTemplatePayment(true);
                } else {
                    if (getCostCenter() != null) {
                        setIsDisableTemplatePayment(false);
                    } else {
                        setIsDisableTemplatePayment(true);
                    }
                }
            }
        } else {
            if (getCostCenterFlex() != null) {
                setIsDisableTemplatePayment(true);
            } else {
                if (getCostCenter() != null) {
                    setIsDisableTemplatePayment(false);
                } else {
                    setIsDisableTemplatePayment(true);
                }
            }
        }

        return (Boolean)getAttributeInternal(ISDISABLETEMPLATEPAYMENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsDisableTemplatePayment
     */
    public void setIsDisableTemplatePayment(Boolean value) {
        populateAttribute(ISDISABLETEMPLATEPAYMENT, value);
    }

    /**Gets the attribute value for the calculated attribute CostCenterFlex
     */
    public String getCostCenterFlex() {
        return (String)getAttributeInternal(COSTCENTERFLEX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CostCenterFlex
     */
    public void setCostCenterFlex(String value) {
        setAttributeInternal(COSTCENTERFLEX, value);
    }

    /**Gets the attribute value for the calculated attribute IsDisableTemplatePaymentFlex
     */
    public Boolean getIsDisableTemplatePaymentFlex() {

        if (getIsRespFranchise() != null) {
            if (getIsRespFranchise().booleanValue()) {
                setIsDisableTemplatePaymentFlex(true);
            } else {
                if (getIsDisableTemplatePayment() != null) {
                    boolean isDisable = getIsDisableTemplatePayment();
                    setIsDisableTemplatePaymentFlex(!isDisable);
                } else {
                    setIsDisableTemplatePaymentFlex(false);
                }
            }
        } else {
            if (getIsDisableTemplatePayment() != null) {
                boolean isDisable = getIsDisableTemplatePayment();
                setIsDisableTemplatePaymentFlex(!isDisable);
            } else {
                setIsDisableTemplatePaymentFlex(false);
            }
        }

        return (Boolean)getAttributeInternal(ISDISABLETEMPLATEPAYMENTFLEX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsDisableTemplatePaymentFlex
     */
    public void setIsDisableTemplatePaymentFlex(Boolean value) {
        populateAttribute(ISDISABLETEMPLATEPAYMENTFLEX, value);
    }

    /**Gets the attribute value for the calculated attribute IsRespFranchise
     */
    public Boolean getIsRespFranchise() {
        return (Boolean)getAttributeInternal(ISRESPFRANCHISE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRespFranchise
     */
    public void setIsRespFranchise(Boolean value) {
        setAttributeInternal(ISRESPFRANCHISE, value);
    }


    /**Gets the attribute value for the calculated attribute ApproverAltId
     */
    public Number getApproverAltId() {
        return (Number)getAttributeInternal(APPROVERALTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverAltId
     */
    public void setApproverAltId(Number value) {
        setAttributeInternal(APPROVERALTID, value);
    }

    /**Gets the attribute value for the calculated attribute FullNameApproverAlt
     */
    public String getFullNameApproverAlt() {
        return (String)getAttributeInternal(FULLNAMEAPPROVERALT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FullNameApproverAlt
     */
    public void setFullNameApproverAlt(String value) {
        setAttributeInternal(FULLNAMEAPPROVERALT, value);
    }


    /**Gets the attribute value for the calculated attribute IsVisibleApproverAlt
     */
    public Boolean getIsVisibleApproverAlt() {

        if (getCostCenterFlex() != null) {
            setIsVisibleApproverAlt(true);
        } else {
            setIsVisibleApproverAlt(false);
            setApproverAltId(null);
        }

        return (Boolean)getAttributeInternal(ISVISIBLEAPPROVERALT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsVisibleApproverAlt
     */
    public void setIsVisibleApproverAlt(Boolean value) {
        setAttributeInternal(ISVISIBLEAPPROVERALT, value);
    }

    /**Gets the attribute value for the calculated attribute Reason
     */
    public String getReason() {
        return (String)getAttributeInternal(REASON);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Reason
     */
    public void setReason(String value) {
        setAttributeInternal(REASON, value);
    }

    /**Gets the attribute value for the calculated attribute Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**Gets the attribute value for the calculated attribute ApproverNameAlt
     */
    public String getApproverNameAlt() {
        return (String)getAttributeInternal(APPROVERNAMEALT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ApproverNameAlt
     */
    public void setApproverNameAlt(String value) {
        setAttributeInternal(APPROVERNAMEALT, value);
    }


    /**Gets the attribute value for the calculated attribute OperatingUnit
     */
    public String getOperatingUnit() {
        return (String)getAttributeInternal(OPERATINGUNIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**Gets the attribute value for the calculated attribute Origin
     */
    public String getOrigin() {
        return (String)getAttributeInternal(ORIGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Origin
     */
    public void setOrigin(String value) {
        System.out.println("View Row setOrigin value:" + value);
        setAttributeInternal(ORIGIN, value);
    }

    /**Gets the attribute value for the calculated attribute VcMeaningxx
     */
    public String getVcMeaningxx() {
        return (String)getAttributeInternal(VCMEANINGXX);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute VcMeaningxx
     */
    public void setVcMeaningxx(String value) {
        /**Agregado 29/Jul/2015 para que no dezaparezca en caso de no elegir un centro de costos alterno existente
      * Enmascarar targeta virtual **/
        if (null != value) {
            setAttributeInternal(VCMEANINGXX, value);
        }

    }

    /**Gets the attribute value for DEPART_TIME using the alias name DepartTime
     */
    public String getDepartTime() {
        return (String)getAttributeInternal(DEPARTTIME);
    }

    /**Sets <code>value</code> as attribute value for DEPART_TIME using the alias name DepartTime
     */
    public void setDepartTime(String value) {
        setAttributeInternal(DEPARTTIME, value);
    }

    /**Gets the attribute value for ARRIVAL_TIME using the alias name ArrivalTime
     */
    public String getArrivalTime() {
        return (String)getAttributeInternal(ARRIVALTIME);
    }

    /**Sets <code>value</code> as attribute value for ARRIVAL_TIME using the alias name ArrivalTime
     */
    public void setArrivalTime(String value) {
        setAttributeInternal(ARRIVALTIME, value);
    }
}
