package xxgam.oracle.apps.xbol.maf.lov.server.common;

import oracle.jbo.ViewObject;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface XxGamMaCurrencyLovVO extends ViewObject {
    void searchCurrencyByCode(String currencyCode);
}
