package xxgam.oracle.apps.xbol.maf.lov.server.common;

import oracle.jbo.common.JboResourceBundle;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public class XxGamMaLookupGenericLovVORowImplMsgBundle extends JboResourceBundle {


    static final Object[][] sMessageStrings = 
    {
{ "pViewApplication_DISPLAYHINT", "Hide" },
{ "pLookupType_DISPLAYHINT", "Hide" }};

    /**This is the default constructor (do not remove)
     */
    public XxGamMaLookupGenericLovVORowImplMsgBundle() {
    }

    /**@return an array of key-value pairs.
     */
    public Object[][] getContents() {
        return super.getMergedArray(sMessageStrings, super.getContents());
    }
}
