package xxgam.oracle.apps.xbol.maf.lov.server.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---------------------------------------------------------------------
public interface XxGamMaSupervisorLovVO extends ViewObject {
    void searchSupervisorById(Number supervisorId);
}
