package xxgam.oracle.apps.inv.moveorder.siz.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamKitItemsInfoVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxGamKitItemsInfoVOImpl() {
    }


}
