package xxgam.oracle.apps.xbol.maf.lov.server.client;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaLookupGenericLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaLookupGenericLovVOClient extends ViewUsageImpl implements XxGamMaLookupGenericLovVO {
    /**This is the default constructor (do not remove)
     */
    public XxGamMaLookupGenericLovVOClient() {
    }


    public void searchLookup(String strLookupType, Number numViewApplication) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this, "searchLookup", 
                                                               new String[] { "java.lang.String", 
                                                                              "oracle.jbo.domain.Number" }, 
                                                               new Object[] { strLookupType, 
                                                                              numViewApplication });
        return;
    }
}
