package xxgam.oracle.apps.xbol.maf.lov.server.client;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaCostCenterByPersonIdLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaCostCenterByPersonIdLovVOClient extends ViewUsageImpl implements XxGamMaCostCenterByPersonIdLovVO {
    /**This is the default constructor (do not remove)
     */
    public XxGamMaCostCenterByPersonIdLovVOClient() {
    }


    public void setEmployeePersonId(Number employeePersonId) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this, "setEmployeePersonId", 
                                                               new String[] { "oracle.jbo.domain.Number" }, 
                                                               new Object[] { employeePersonId });
        return;
    }

    public void searchCostCenterByPersonId(Number numPersonId, 
                                           String vcLookupType) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this, "searchCostCenterByPersonId", 
                                                               new String[] { "oracle.jbo.domain.Number", 
                                                                              "java.lang.String" }, 
                                                               new Object[] { numPersonId, 
                                                                              vcLookupType });
        return;
    }

    public void setVcLookupType(String vcLookupType) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this, "setVcLookupType", 
                                                               new String[] { "java.lang.String" }, 
                                                               new Object[] { vcLookupType });
        return;
    }
}
