package xxgam.oracle.apps.xbol.maf.lov.server.client;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaTypePaymentLovVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaTypePaymentLovVOClient extends ViewUsageImpl implements XxGamMaTypePaymentLovVO {
    /**This is the default constructor (do not remove)
     */
    public XxGamMaTypePaymentLovVOClient() {
    }

    public void searchTypePaymentByTemplateId(Number templateId) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this, "searchTypePaymentByTemplateId", 
                                                               new String[] { "oracle.jbo.domain.Number" }, 
                                                               new Object[] { templateId });
        return;
    }
}
