package xxgam.oracle.apps.xbol.maf.lov.server.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import oracle.jbo.domain.Number;

import xxgam.oracle.apps.xbol.maf.lov.server.common.XxGamMaUserDataLovVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamMaUserDataLovVOClient extends ViewUsageImpl implements XxGamMaUserDataLovVO {
    /**This is the default constructor (do not remove)
     */
    public XxGamMaUserDataLovVOClient() {
    }


    public void searchUser(String strUserName, String strVendorType) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"searchUser",new String [] {"java.lang.String","java.lang.String"},new Object[] {strUserName, strVendorType});
        return;
    }

    public void searchUserByPersonId(Number personId, String strVendorType) {
        Object _ret = 
            getApplicationModuleProxy().riInvokeExportedMethod(this,"searchUserByPersonId",new String [] {"oracle.jbo.domain.Number","java.lang.String"},new Object[] {personId, strVendorType});
        return;
    }
}
