package xxgam.oracle.apps.inv.moveorder.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xXGamV2InvSoliDtlVORowImpl extends OAViewRowImpl
{
  public static final int DOTAID = 0;
  public static final int UNIFORMTYPECOD = 1;
  public static final int NOMENCLATURE = 2;
  public static final int NPCOD = 3;
  public static final int MEASUREUNITCOD = 4;
  public static final int CYCLECOD = 5;
  public static final int PLANTAQTY = 6;
  public static final int EVENTQTY = 7;
  public static final int TALLAID = 8;
  public static final int TALLANBR = 9;
  public static final int QTYNBR = 10;
  public static final int INVENTORYID = 11;
  public static final int INVORGID = 12;
  public static final int TALLADEVDISABLED = 13;
  public static final int CANTIDADDEVDISABLED = 14;
  public static final int TALLADEVDISABLEDFLAG = 15;
  public static final int CANTIDADDEVDISABLEDFLAG = 16;
  public static final int STATUSDSP = 17;
  public static final int SUSTITUCIONSWITCHER = 18;
  public static final int OBSERVACIONESSLTUD = 19;

  /**This is the default constructor (do not remove)
   */
  public xXGamV2InvSoliDtlVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute DotaId
   */
  public Number getDotaId()
  {
    return (Number) getAttributeInternal(DOTAID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute DotaId
   */
  public void setDotaId(Number value)
  {
    setAttributeInternal(DOTAID, value);
  }

  /**Gets the attribute value for the calculated attribute UniformTypeCod
   */
  public String getUniformTypeCod()
  {
    return (String) getAttributeInternal(UNIFORMTYPECOD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute UniformTypeCod
   */
  public void setUniformTypeCod(String value)
  {
    setAttributeInternal(UNIFORMTYPECOD, value);
  }

  /**Gets the attribute value for the calculated attribute Nomenclature
   */
  public String getNomenclature()
  {
    return (String) getAttributeInternal(NOMENCLATURE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Nomenclature
   */
  public void setNomenclature(String value)
  {
    setAttributeInternal(NOMENCLATURE, value);
  }

  /**Gets the attribute value for the calculated attribute NpCod
   */
  public String getNpCod()
  {
    return (String) getAttributeInternal(NPCOD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute NpCod
   */
  public void setNpCod(String value)
  {
    setAttributeInternal(NPCOD, value);
  }

  /**Gets the attribute value for the calculated attribute MeasureUnitCod
   */
  public String getMeasureUnitCod()
  {
    return (String) getAttributeInternal(MEASUREUNITCOD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute MeasureUnitCod
   */
  public void setMeasureUnitCod(String value)
  {
    setAttributeInternal(MEASUREUNITCOD, value);
  }

  /**Gets the attribute value for the calculated attribute CycleCod
   */
  public String getCycleCod()
  {
    return (String) getAttributeInternal(CYCLECOD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CycleCod
   */
  public void setCycleCod(String value)
  {
    setAttributeInternal(CYCLECOD, value);
  }

  /**Gets the attribute value for the calculated attribute PlantaQty
   */
  public Number getPlantaQty()
  {
    return (Number) getAttributeInternal(PLANTAQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PlantaQty
   */
  public void setPlantaQty(Number value)
  {
    setAttributeInternal(PLANTAQTY, value);
  }

  /**Gets the attribute value for the calculated attribute EventQty
   */
  public Number getEventQty()
  {
    return (Number) getAttributeInternal(EVENTQTY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EventQty
   */
  public void setEventQty(Number value)
  {
    setAttributeInternal(EVENTQTY, value);
  }

  /**Gets the attribute value for the calculated attribute TallaId
   */
  public Number getTallaId()
  {
    return (Number) getAttributeInternal(TALLAID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TallaId
   */
  public void setTallaId(Number value)
  {
    setAttributeInternal(TALLAID, value);
  }

  /**Gets the attribute value for the calculated attribute TallaNbr
   */
  public String getTallaNbr()
  {
    return (String) getAttributeInternal(TALLANBR);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TallaNbr
   */
  public void setTallaNbr(String value)
  {
    setAttributeInternal(TALLANBR, value);
  }

  /**Gets the attribute value for the calculated attribute QtyNbr
   */
  public Number getQtyNbr()
  {
    return (Number) getAttributeInternal(QTYNBR);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute QtyNbr
   */
  public void setQtyNbr(Number value)
  {
    setAttributeInternal(QTYNBR, value);
  }

  /**Gets the attribute value for the calculated attribute InventoryId
   */
  public Number getInventoryId()
  {
    return (Number) getAttributeInternal(INVENTORYID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute InventoryId
   */
  public void setInventoryId(Number value)
  {
    setAttributeInternal(INVENTORYID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case DOTAID:
      return getDotaId();
    case UNIFORMTYPECOD:
      return getUniformTypeCod();
    case NOMENCLATURE:
      return getNomenclature();
    case NPCOD:
      return getNpCod();
    case MEASUREUNITCOD:
      return getMeasureUnitCod();
    case CYCLECOD:
      return getCycleCod();
    case PLANTAQTY:
      return getPlantaQty();
    case EVENTQTY:
      return getEventQty();
    case TALLAID:
      return getTallaId();
    case TALLANBR:
      return getTallaNbr();
    case QTYNBR:
      return getQtyNbr();
    case INVENTORYID:
      return getInventoryId();
    case INVORGID:
      return getInvOrgId();
    case TALLADEVDISABLED:
      return getTallaDevDisabled();
    case CANTIDADDEVDISABLED:
      return getCantidadDevDisabled();
    case TALLADEVDISABLEDFLAG:
      return getTallaDevDisabledFlag();
    case CANTIDADDEVDISABLEDFLAG:
      return getCantidadDevDisabledFlag();
    case STATUSDSP:
      return getStatusDsp();
    case SUSTITUCIONSWITCHER:
      return getSustitucionSwitcher();
    case OBSERVACIONESSLTUD:
      return getObservacionesSltud();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case DOTAID:
      setDotaId((Number)value);
      return;
    case UNIFORMTYPECOD:
      setUniformTypeCod((String)value);
      return;
    case NOMENCLATURE:
      setNomenclature((String)value);
      return;
    case NPCOD:
      setNpCod((String)value);
      return;
    case MEASUREUNITCOD:
      setMeasureUnitCod((String)value);
      return;
    case CYCLECOD:
      setCycleCod((String)value);
      return;
    case PLANTAQTY:
      setPlantaQty((Number)value);
      return;
    case EVENTQTY:
      setEventQty((Number)value);
      return;
    case TALLAID:
      setTallaId((Number)value);
      return;
    case TALLANBR:
      setTallaNbr((String)value);
      return;
    case QTYNBR:
      setQtyNbr((Number)value);
      return;
    case INVENTORYID:
      setInventoryId((Number)value);
      return;
    case INVORGID:
      setInvOrgId((Number)value);
      return;
    case TALLADEVDISABLED:
      setTallaDevDisabled((Boolean)value);
      return;
    case CANTIDADDEVDISABLED:
      setCantidadDevDisabled((Boolean)value);
      return;
    case TALLADEVDISABLEDFLAG:
      setTallaDevDisabledFlag((String)value);
      return;
    case CANTIDADDEVDISABLEDFLAG:
      setCantidadDevDisabledFlag((String)value);
      return;
    case STATUSDSP:
      setStatusDsp((String)value);
      return;
    case SUSTITUCIONSWITCHER:
      setSustitucionSwitcher((String)value);
      return;
    case OBSERVACIONESSLTUD:
      setObservacionesSltud((String)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for the calculated attribute InvOrgId
   */
  public Number getInvOrgId()
  {
    return (Number) getAttributeInternal(INVORGID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute InvOrgId
   */
  public void setInvOrgId(Number value)
  {
    setAttributeInternal(INVORGID, value);
  }

  /**Gets the attribute value for the calculated attribute TallaDevDisabled
   */
  public Boolean getTallaDevDisabled()
  {
    return (Boolean) getAttributeInternal(TALLADEVDISABLED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TallaDevDisabled
   */
  public void setTallaDevDisabled(Boolean value)
  {
    setAttributeInternal(TALLADEVDISABLED, value);
  }

  /**Gets the attribute value for the calculated attribute CantidadDevDisabled
   */
  public Boolean getCantidadDevDisabled()
  {
    return (Boolean) getAttributeInternal(CANTIDADDEVDISABLED);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CantidadDevDisabled
   */
  public void setCantidadDevDisabled(Boolean value)
  {
    setAttributeInternal(CANTIDADDEVDISABLED, value);
  }

  /**Gets the attribute value for the calculated attribute TallaDevDisabledFlag
   */
  public String getTallaDevDisabledFlag()
  {
    return (String) getAttributeInternal(TALLADEVDISABLEDFLAG);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TallaDevDisabledFlag
   */
  public void setTallaDevDisabledFlag(String value)
  {
    setAttributeInternal(TALLADEVDISABLEDFLAG, value);
  }

  /**Gets the attribute value for the calculated attribute CantidadDevDisabledFlag
   */
  public String getCantidadDevDisabledFlag()
  {
    return (String) getAttributeInternal(CANTIDADDEVDISABLEDFLAG);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CantidadDevDisabledFlag
   */
  public void setCantidadDevDisabledFlag(String value)
  {
    setAttributeInternal(CANTIDADDEVDISABLEDFLAG, value);
  }

  /**Gets the attribute value for the calculated attribute StatusDsp
   */
  public String getStatusDsp()
  {
    return (String) getAttributeInternal(STATUSDSP);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute StatusDsp
   */
  public void setStatusDsp(String value)
  {
    setAttributeInternal(STATUSDSP, value);
  }

  /**Gets the attribute value for the calculated attribute SustitucionSwitcher
   */
  public String getSustitucionSwitcher()
  {
    return (String) getAttributeInternal(SUSTITUCIONSWITCHER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute SustitucionSwitcher
   */
  public void setSustitucionSwitcher(String value)
  {
    setAttributeInternal(SUSTITUCIONSWITCHER, value);
  }

  /**Gets the attribute value for the calculated attribute ObservacionesSltud
   */
  public String getObservacionesSltud()
  {
    return (String) getAttributeInternal(OBSERVACIONESSLTUD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ObservacionesSltud
   */
  public void setObservacionesSltud(String value)
  {
    setAttributeInternal(OBSERVACIONESSLTUD, value);
  }
}
