package xxgam.oracle.apps.inv.moveorder.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xXGamInvSoliSummaryVORowImpl extends OAViewRowImpl {
    public static final int SOLIID = 0;
    public static final int NROSOLICITUD = 1;
    public static final int STATUS = 2;
    public static final int STATUSDSP = 3;
    public static final int SOLIDATE = 4;
    public static final int PERSONID = 5;
    public static final int UPDATESWITCHER = 6;
    public static final int PRINTSWITCHER = 7;
    public static final int SELECTFLAG = 8;
    public static final int EMPLOYEENUMBER = 9;
    public static final int CREATEDBY = 10;
    public static final int SELECTFLAG1 = 11;
    public static final int LINKTRANSIENT = 12;
    public static final int XXGAMINVSOLIVO = 13;

    /**This is the default constructor (do not remove)
     */
    public xXGamInvSoliSummaryVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SoliId
     */
    public Number getSoliId() {
        return (Number)getAttributeInternal(SOLIID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SoliId
     */
    public void setSoliId(Number value) {
        setAttributeInternal(SOLIID, value);
    }

    /**Gets the attribute value for the calculated attribute NroSolicitud
     */
    public String getNroSolicitud() {
        return (String)getAttributeInternal(NROSOLICITUD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NroSolicitud
     */
    public void setNroSolicitud(String value) {
        setAttributeInternal(NROSOLICITUD, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute StatusDsp
     */
    public String getStatusDsp() {
        return (String)getAttributeInternal(STATUSDSP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StatusDsp
     */
    public void setStatusDsp(String value) {
        setAttributeInternal(STATUSDSP, value);
    }

    /**Gets the attribute value for the calculated attribute SoliDate
     */
    public Date getSoliDate() {
        return (Date)getAttributeInternal(SOLIDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SoliDate
     */
    public void setSoliDate(Date value) {
        setAttributeInternal(SOLIDATE, value);
    }

    /**Gets the attribute value for the calculated attribute PersonId
     */
    public Number getPersonId() {
        return (Number)getAttributeInternal(PERSONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**Gets the attribute value for the calculated attribute UpdateSwitcher
     */
    public String getUpdateSwitcher() {
        return (String)getAttributeInternal(UPDATESWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UpdateSwitcher
     */
    public void setUpdateSwitcher(String value) {
        setAttributeInternal(UPDATESWITCHER, value);
    }

    /**Gets the attribute value for the calculated attribute PrintSwitcher
     */
    public String getPrintSwitcher() {
        return (String)getAttributeInternal(PRINTSWITCHER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PrintSwitcher
     */
    public void setPrintSwitcher(String value) {
        setAttributeInternal(PRINTSWITCHER, value);
    }

    /**Gets the attribute value for the calculated attribute SelectFlag
     */
    public String getSelectFlag() {
        return (String)getAttributeInternal(SELECTFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectFlag
     */
    public void setSelectFlag(String value) {
        setAttributeInternal(SELECTFLAG, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeeNumber
     */
    public String getEmployeeNumber() {
        return (String)getAttributeInternal(EMPLOYEENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
     */
    public void setEmployeeNumber(String value) {
        setAttributeInternal(EMPLOYEENUMBER, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute SelectFlag1
     */
    public String getSelectFlag1() {
        return (String)getAttributeInternal(SELECTFLAG1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectFlag1
     */
    public void setSelectFlag1(String value) {
        setAttributeInternal(SELECTFLAG1, value);
    }

    /**Gets the attribute value for the calculated attribute LinkTransient
     */
    public String getLinkTransient() {
        return (String)getAttributeInternal(LINKTRANSIENT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LinkTransient
     */
    public void setLinkTransient(String value) {
        setAttributeInternal(LINKTRANSIENT, value);
    }

    /**Gets the associated <code>Row</code> using master-detail link xXGamInvSoliVO
     */
    public Row getxXGamInvSoliVO() {
        return (Row)getAttributeInternal(XXGAMINVSOLIVO);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SOLIID:
            return getSoliId();
        case NROSOLICITUD:
            return getNroSolicitud();
        case STATUS:
            return getStatus();
        case STATUSDSP:
            return getStatusDsp();
        case SOLIDATE:
            return getSoliDate();
        case PERSONID:
            return getPersonId();
        case UPDATESWITCHER:
            return getUpdateSwitcher();
        case PRINTSWITCHER:
            return getPrintSwitcher();
        case SELECTFLAG:
            return getSelectFlag();
        case EMPLOYEENUMBER:
            return getEmployeeNumber();
        case CREATEDBY:
            return getCreatedBy();
        case SELECTFLAG1:
            return getSelectFlag1();
        case LINKTRANSIENT:
            return getLinkTransient();
        case XXGAMINVSOLIVO:
            return getxXGamInvSoliVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SOLIID:
            setSoliId((Number)value);
            return;
        case NROSOLICITUD:
            setNroSolicitud((String)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case STATUSDSP:
            setStatusDsp((String)value);
            return;
        case SOLIDATE:
            setSoliDate((Date)value);
            return;
        case PERSONID:
            setPersonId((Number)value);
            return;
        case UPDATESWITCHER:
            setUpdateSwitcher((String)value);
            return;
        case PRINTSWITCHER:
            setPrintSwitcher((String)value);
            return;
        case SELECTFLAG:
            setSelectFlag((String)value);
            return;
        case EMPLOYEENUMBER:
            setEmployeeNumber((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case SELECTFLAG1:
            setSelectFlag1((String)value);
            return;
        case LINKTRANSIENT:
            setLinkTransient((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
