package xxgam.oracle.apps.inv.moveorder.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class xXGamV2InvSoliVORowImpl extends OAViewRowImpl
{
  public static final int KITID = 0;
  public static final int KITCOD = 1;
  public static final int KITDES = 2;
  public static final int PERSONID = 3;
  public static final int EMPLOYEENUMBER = 4;
  public static final int RFC = 5;
  public static final int CATEGORY = 6;
  public static final int ADSCRIPTION = 7;
  public static final int CONTDUEDATE = 8;
  public static final int STATION = 9;
  public static final int COSTCENTER = 10;
  public static final int EXPENSEACC = 11;
  public static final int EXPENSEDESC = 12;
  public static final int FULLNAME = 13;
  public static final int XXGAMINVASSIGNEXCEPT = 14;
  public static final int USERID = 15;
  public static final int FECHASOLICITUD = 16;

  /**This is the default constructor (do not remove)
   */
  public xXGamV2InvSoliVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute KitId
   */
  public Number getKitId()
  {
    return (Number) getAttributeInternal(KITID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KitId
   */
  public void setKitId(Number value)
  {
    setAttributeInternal(KITID, value);
  }

  /**Gets the attribute value for the calculated attribute KitCod
   */
  public String getKitCod()
  {
    return (String) getAttributeInternal(KITCOD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KitCod
   */
  public void setKitCod(String value)
  {
    setAttributeInternal(KITCOD, value);
  }

  /**Gets the attribute value for the calculated attribute KitDes
   */
  public String getKitDes()
  {
    return (String) getAttributeInternal(KITDES);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KitDes
   */
  public void setKitDes(String value)
  {
    setAttributeInternal(KITDES, value);
  }

  /**Gets the attribute value for the calculated attribute PersonId
   */
  public Number getPersonId()
  {
    return (Number) getAttributeInternal(PERSONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonId
   */
  public void setPersonId(Number value)
  {
    setAttributeInternal(PERSONID, value);
  }

  /**Gets the attribute value for the calculated attribute EmployeeNumber
   */
  public String getEmployeeNumber()
  {
    return (String) getAttributeInternal(EMPLOYEENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeNumber
   */
  public void setEmployeeNumber(String value)
  {
    setAttributeInternal(EMPLOYEENUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute Rfc
   */
  public String getRfc()
  {
    return (String) getAttributeInternal(RFC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Rfc
   */
  public void setRfc(String value)
  {
    setAttributeInternal(RFC, value);
  }

  /**Gets the attribute value for the calculated attribute Category
   */
  public String getCategory()
  {
    return (String) getAttributeInternal(CATEGORY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Category
   */
  public void setCategory(String value)
  {
    setAttributeInternal(CATEGORY, value);
  }

  /**Gets the attribute value for the calculated attribute Adscription
   */
  public String getAdscription()
  {
    return (String) getAttributeInternal(ADSCRIPTION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Adscription
   */
  public void setAdscription(String value)
  {
    setAttributeInternal(ADSCRIPTION, value);
  }

  /**Gets the attribute value for the calculated attribute ContDueDate
   */
  public Date getContDueDate()
  {
    return (Date) getAttributeInternal(CONTDUEDATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ContDueDate
   */
  public void setContDueDate(Date value)
  {
    setAttributeInternal(CONTDUEDATE, value);
  }

  /**Gets the attribute value for the calculated attribute Station
   */
  public String getStation()
  {
    return (String) getAttributeInternal(STATION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Station
   */
  public void setStation(String value)
  {
    setAttributeInternal(STATION, value);
  }

  /**Gets the attribute value for the calculated attribute CostCenter
   */
  public String getCostCenter()
  {
    return (String) getAttributeInternal(COSTCENTER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CostCenter
   */
  public void setCostCenter(String value)
  {
    setAttributeInternal(COSTCENTER, value);
  }

  /**Gets the attribute value for the calculated attribute ExpenseAcc
   */
  public Number getExpenseAcc()
  {
    return (Number) getAttributeInternal(EXPENSEACC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ExpenseAcc
   */
  public void setExpenseAcc(Number value)
  {
    setAttributeInternal(EXPENSEACC, value);
  }

  /**Gets the attribute value for the calculated attribute ExpenseDesc
   */
  public String getExpenseDesc()
  {
    return (String) getAttributeInternal(EXPENSEDESC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute ExpenseDesc
   */
  public void setExpenseDesc(String value)
  {
    setAttributeInternal(EXPENSEDESC, value);
  }

  /**Gets the attribute value for the calculated attribute FullName
   */
  public String getFullName()
  {
    return (String) getAttributeInternal(FULLNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FullName
   */
  public void setFullName(String value)
  {
    setAttributeInternal(FULLNAME, value);
  }

  /**Gets the attribute value for the calculated attribute XxGamInvAssignExcept
   */
  public String getXxGamInvAssignExcept()
  {
    return (String) getAttributeInternal(XXGAMINVASSIGNEXCEPT);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute XxGamInvAssignExcept
   */
  public void setXxGamInvAssignExcept(String value)
  {
    setAttributeInternal(XXGAMINVASSIGNEXCEPT, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case KITID:
      return getKitId();
    case KITCOD:
      return getKitCod();
    case KITDES:
      return getKitDes();
    case PERSONID:
      return getPersonId();
    case EMPLOYEENUMBER:
      return getEmployeeNumber();
    case RFC:
      return getRfc();
    case CATEGORY:
      return getCategory();
    case ADSCRIPTION:
      return getAdscription();
    case CONTDUEDATE:
      return getContDueDate();
    case STATION:
      return getStation();
    case COSTCENTER:
      return getCostCenter();
    case EXPENSEACC:
      return getExpenseAcc();
    case EXPENSEDESC:
      return getExpenseDesc();
    case FULLNAME:
      return getFullName();
    case XXGAMINVASSIGNEXCEPT:
      return getXxGamInvAssignExcept();
    case USERID:
      return getUserId();
    case FECHASOLICITUD:
      return getFechaSolicitud();
    default:
      return super.getAttrInvokeAccessor(index, attrDef);
    }
  }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
    switch (index)
    {
    case KITID:
      setKitId((Number)value);
      return;
    case KITCOD:
      setKitCod((String)value);
      return;
    case KITDES:
      setKitDes((String)value);
      return;
    case PERSONID:
      setPersonId((Number)value);
      return;
    case EMPLOYEENUMBER:
      setEmployeeNumber((String)value);
      return;
    case RFC:
      setRfc((String)value);
      return;
    case CATEGORY:
      setCategory((String)value);
      return;
    case ADSCRIPTION:
      setAdscription((String)value);
      return;
    case CONTDUEDATE:
      setContDueDate((Date)value);
      return;
    case STATION:
      setStation((String)value);
      return;
    case COSTCENTER:
      setCostCenter((String)value);
      return;
    case EXPENSEACC:
      setExpenseAcc((Number)value);
      return;
    case EXPENSEDESC:
      setExpenseDesc((String)value);
      return;
    case FULLNAME:
      setFullName((String)value);
      return;
    case XXGAMINVASSIGNEXCEPT:
      setXxGamInvAssignExcept((String)value);
      return;
    case USERID:
      setUserId((Number)value);
      return;
    case FECHASOLICITUD:
      setFechaSolicitud((Date)value);
      return;
    default:
      super.setAttrInvokeAccessor(index, value, attrDef);
      return;
    }
  }

  /**Gets the attribute value for the calculated attribute UserId
   */
  public Number getUserId()
  {
    return (Number) getAttributeInternal(USERID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute UserId
   */
  public void setUserId(Number value)
  {
    setAttributeInternal(USERID, value);
  }

  /**Gets the attribute value for the calculated attribute FechaSolicitud
   */
  public Date getFechaSolicitud()
  {
    return (Date) getAttributeInternal(FECHASOLICITUD);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute FechaSolicitud
   */
  public void setFechaSolicitud(Date value)
  {
    setAttributeInternal(FECHASOLICITUD, value);
  }
}
